define({
    taskUrl: "Ж_Task URL_Я",
    serviceURLPlaceholder: "Ж_Please input Geoprocessing task URL_Я",
    ok: "Ж_OK_Я",
    cancel: "Ж_Cancel_Я",
    layer: "Ж_Layer_Я",
    action: "Ж_Action_Я",
    input: "Ж_Input_Я",
    output: "Ж_Output_Я",
    name: "Ж_Name_Я",
    type: "Ж_Type_Я",
    required: "Ж_Required_Я",
    layerOrder: "Ж_Layer order_Я",
    options: "Ж_Options_Я",
    defaultValue: "Ж_Default Value_Я",
    inputFeatureBy: "Ж_Input Feature by_Я",
    renderer: "Ж_Renderer_Я",
    displayType: "Ж_Display type_Я",
    label: "Ж_Label_Я",
    tooltip: "Ж_Tooltip_Я",
    visible: "Ж_Visible_Я",
    helpUrl: "Ж_Help URL_Я",
    useResultMapService: "Ж_Use the drawing options of result map service_Я",
    drawOnMap: "Ж_Interactively drawing on the map_Я",
    selectLayer: "Ж_Selecting a layer from the map_Я",
    url: "Ж_URL_Я",
    symbol: "Ж_Symbol_Я",
    shareResults: "Ж_Add result as operational layer_Я"
});