define({
    executeQueryTip: "بيت_Click one of the following items to execute query._لاحقة",
    invalidConfig: "بيت_Invalid config. Please use Query setting page to get correct config._لاحقة",
    queryParams: "بيت_Query Parameters_لاحقة",
    parameters: "بيت_Parameters_لاحقة",
    queries: "بيت_Queries_لاحقة",
    apply: "بيت_Apply_لاحقة",
    queryResults: "بيت_Query Results_لاحقة",
    clear: "بيت_Clear_لاحقة",
    noResults: "بيت_No results_لاحقة",
    queryError: "بيت_Query failed !_لاحقة",
    numberFound: "بيت_Number of features found_لاحقة",
    mapExtentTip:"بيت_Limit the results to the current map extent._لاحقة",
    noValue:"بيت_No value_لاحقة",
    and:"بيت_and_لاحقة",
    friendlyDatePattern:"بيت_MM/dd/yyyy_لاحقة",
    stringOperatorIs: "بيت_is_لاحقة", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "بيت_is not_لاحقة",
    stringOperatorStartsWith: "بيت_starts with_لاحقة",
    stringOperatorEndsWith: "بيت_ends with_لاحقة",
    stringOperatorContains: "بيت_contains_لاحقة",
    stringOperatorDoesNotContain: "بيت_does not contain_لاحقة",
    stringOperatorIsBlank: "بيت_is blank_لاحقة",
    stringOperatorIsNotBlank: "بيت_is not blank_لاحقة",
    dateOperatorIsOn: "بيت_is on_لاحقة", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "بيت_is not on_لاحقة",
    dateOperatorIsBefore: "بيت_is before_لاحقة",
    dateOperatorIsAfter: "بيت_is after_لاحقة",
    dateOperatorDays: "بيت_days_لاحقة",
    dateOperatorWeeks: "بيت_weeks_لاحقة", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "بيت_months_لاحقة",
    dateOperatorInTheLast: "بيت_in the last_لاحقة",
    dateOperatorNotInTheLast: "بيت_not in the last_لاحقة",
    dateOperatorIsBetween: "بيت_is between_لاحقة",
    dateOperatorIsNotBetween: "بيت_is not between_لاحقة",
    dateOperatorIsBlank: "بيت_is blank_لاحقة",
    dateOperatorIsNotBlank: "بيت_is not blank_لاحقة",
    numberOperatorIs: "بيت_is_لاحقة", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "بيت_is not_لاحقة",
    numberOperatorIsAtLeast: "بيت_is at least_لاحقة",
    numberOperatorIsLessThan: "بيت_is less than_لاحقة",
    numberOperatorIsAtMost: "بيت_is at most_لاحقة",
    numberOperatorIsGreaterThan: "بيت_is greater than_لاحقة",
    numberOperatorIsBetween: "بيت_is between_لاحقة",
    numberOperatorIsNotBetween: "بيت_is not between_لاحقة",
    numberOperatorIsBlank: "بيت_is blank_لاحقة",
    numberOperatorIsNotBlank: "بيت_is not blank_لاحقة"
});