define({
    taskUrl: "須_Task URL_鷗",
    serviceURLPlaceholder: "須_Please input Geoprocessing task URL_鷗",
    ok: "須_OK_鷗",
    cancel: "須_Cancel_鷗",
    layer: "須_Layer_鷗",
    action: "須_Action_鷗",
    input: "須_Input_鷗",
    output: "須_Output_鷗",
    name: "須_Name_鷗",
    type: "須_Type_鷗",
    required: "須_Required_鷗",
    layerOrder: "須_Layer order_鷗",
    options: "須_Options_鷗",
    defaultValue: "須_Default Value_鷗",
    inputFeatureBy: "須_Input Feature by_鷗",
    renderer: "須_Renderer_鷗",
    displayType: "須_Display type_鷗",
    label: "須_Label_鷗",
    tooltip: "須_Tooltip_鷗",
    visible: "須_Visible_鷗",
    helpUrl: "須_Help URL_鷗",
    useResultMapService: "須_Use the drawing options of result map service_鷗",
    drawOnMap: "須_Interactively drawing on the map_鷗",
    selectLayer: "須_Selecting a layer from the map_鷗",
    url: "須_URL_鷗",
    symbol: "須_Symbol_鷗",
    shareResults: "須_Add result as operational layer_鷗"
});