define({
    ok: "須_OK_鷗",
    cancel: "須_Cancel_鷗",
    exportMessage: "須_Export data to CSV file?_鷗",
    exportFiles: "須_Export to CSV_鷗",
    options: "須_Options_鷗",
    zoomto: "須_Zoom to_鷗",
    highlight: "須_Highlight Graphics_鷗",
    selectAll: "須_Select All Pages_鷗",
    selectPage: "須_Select Current Page_鷗",
    clearSelection: "須_Clear Selection_鷗",
    filterByExtent: "須_Filter by Map Extent_鷗",
    refresh: "須_Refresh_鷗",
    selected: "須_selected_鷗",
    transparent: "須_Transparent Mode_鷗",
    indicate: "須_Locate Selection_鷗",
    columns: "須_Show/Hide Columns_鷗",
    selectionSymbol: "須_Selection Symbol_鷗",
    closeMessage: "須_Hide table[Show it again in layer list]_鷗",
    dataNotAvailable: "須_Data not available!<br>Click [Refresh] button to have a try_鷗"
});