define({
    showArcgisBasemaps: "ø_Show ArcGIS Basemaps_å",
    add: "ø_Click to add a new basemap_å",
    edit: "ø_Properties_å",
    title: "ø_Title_å",
    thumbnail: "ø_Thumbnail_å",
    thumbnailHint: "ø_Click image to update_å",
    url: "ø_URL_å",
    addlayer: "ø_Add layer_å",
    actions: "ø_Actions_å",
    warning: "ø_Incorrect input_å",
    save: "ø_Back and Save_å",
    back: "ø_Back and Cancel_å",
    addUrl: "ø_Add URL_å",
    autoCheck: "ø_Auto Check_å",
    checking: "ø_Checking..._å",
    ok: "ø_OK_å",
    cancel: "ø_Cancel_å",
    result: "ø_Save successfully_å",
    spError: "ø_All basemaps added to the gallery need to have the same spatial reference._å"
});