define({
		queries:"한_Queries_빠",
		addNew: "한_Add New_빠",
		setSource: "한_Set Source_빠",
		setQuerySource: "한_Set query source_빠",
		name: "한_Name_빠",
		querySource: "한_Query Source_빠",
		queryName:"한_Query Name_빠",
		queryDefinition:"한_Query Definition_빠",
		resultsSetting:"한_Results Setting_빠",
		resultSettingTip:"한_Define below for showing information about features that are resulted from the query operation._빠",
		resultItemTitle:"한_Result Item Title_빠",
		resultItemContent:"한_Result Item Content_빠",
		fieldsSetTip:"한_Check the fields you want to display. Select a field to change its alias,order it and format it._빠",
		addField:"한_Add Field_빠",
		visibility:"한_Visibility_빠",
		alias:"한_Alias_빠",
		specialType:"한_Special Type_빠",
		actions:"한_Actions_빠",
		none:"한_None_빠",
		link:"한_Link_빠",
		image:"한_Image_빠",
		noField:"한_No field_빠",
		operationalLayerTip:"한_Add result as operational layer_빠",
		setLayerSymbolTip:"한_Set the symbol of query result._빠",
		setSelectedSymbolTip:"한_Set the symbol of selected feature._빠",
		notUseFilter:"한_Don't use filter_빠",
		setSourceTip:"한_Please set query source !_빠",
		setFilterTip:"한_Please set filter correctly !_빠",
		ok:"한_Ok_빠",
		cancel:"한_Cancel_빠"
});