define({
    taskUrl: "ı_Task URL_İ",
    serviceURLPlaceholder: "ı_Please input Geoprocessing task URL_İ",
    ok: "ı_OK_İ",
    cancel: "ı_Cancel_İ",
    layer: "ı_Layer_İ",
    action: "ı_Action_İ",
    input: "ı_Input_İ",
    output: "ı_Output_İ",
    name: "ı_Name_İ",
    type: "ı_Type_İ",
    required: "ı_Required_İ",
    layerOrder: "ı_Layer order_İ",
    options: "ı_Options_İ",
    defaultValue: "ı_Default Value_İ",
    inputFeatureBy: "ı_Input Feature by_İ",
    renderer: "ı_Renderer_İ",
    displayType: "ı_Display type_İ",
    label: "ı_Label_İ",
    tooltip: "ı_Tooltip_İ",
    visible: "ı_Visible_İ",
    helpUrl: "ı_Help URL_İ",
    useResultMapService: "ı_Use the drawing options of result map service_İ",
    drawOnMap: "ı_Interactively drawing on the map_İ",
    selectLayer: "ı_Selecting a layer from the map_İ",
    url: "ı_URL_İ",
    symbol: "ı_Symbol_İ",
    shareResults: "ı_Add result as operational layer_İ"
});