define({
    showArcgisBasemaps: "包含Portal的底图",
    settings: "设置",
    add: "添加新底图",
    edit: "属性",
    title: "标题",
    thumbnail: "缩略图",
    thumbnailHint: "点击图片进行修改",
    url: "URL",
    addlayer: "添加子图层",
    actions: "Actions",
    warning: "输入不正确",
    save: "保存并返回",
    back: "取消并返回",
    addUrl: "添加URL",
    autoCheck: "自动检查",
    checking: "正在检查...",
    ok: "确定",
    cancel: "取消",
    result: "保存成功",
    spError: "添加的底图必须与现有底图拥有相同的空间参考！"
  });