define({
    showArcgisBasemaps: "Ř_Show ArcGIS Basemaps_ů",
    add: "Ř_Click to add a new basemap_ů",
    edit: "Ř_Properties_ů",
    title: "Ř_Title_ů",
    thumbnail: "Ř_Thumbnail_ů",
    thumbnailHint: "Ř_Click image to update_ů",
    url: "Ř_URL_ů",
    addlayer: "Ř_Add layer_ů",
    actions: "Ř_Actions_ů",
    warning: "Ř_Incorrect input_ů",
    save: "Ř_Back and Save_ů",
    back: "Ř_Back and Cancel_ů",
    addUrl: "Ř_Add URL_ů",
    autoCheck: "Ř_Auto Check_ů",
    checking: "Ř_Checking..._ů",
    ok: "Ř_OK_ů",
    cancel: "Ř_Cancel_ů",
    result: "Ř_Save successfully_ů",
    spError: "Ř_All basemaps added to the gallery need to have the same spatial reference._ů"
});