define({
    taskUrl: "ł_Task URL_ą",
    serviceURLPlaceholder: "ł_Please input Geoprocessing task URL_ą",
    ok: "ł_OK_ą",
    cancel: "ł_Cancel_ą",
    layer: "ł_Layer_ą",
    action: "ł_Action_ą",
    input: "ł_Input_ą",
    output: "ł_Output_ą",
    name: "ł_Name_ą",
    type: "ł_Type_ą",
    required: "ł_Required_ą",
    layerOrder: "ł_Layer order_ą",
    options: "ł_Options_ą",
    defaultValue: "ł_Default Value_ą",
    inputFeatureBy: "ł_Input Feature by_ą",
    renderer: "ł_Renderer_ą",
    displayType: "ł_Display type_ą",
    label: "ł_Label_ą",
    tooltip: "ł_Tooltip_ą",
    visible: "ł_Visible_ą",
    helpUrl: "ł_Help URL_ą",
    useResultMapService: "ł_Use the drawing options of result map service_ą",
    drawOnMap: "ł_Interactively drawing on the map_ą",
    selectLayer: "ł_Selecting a layer from the map_ą",
    url: "ł_URL_ą",
    symbol: "ł_Symbol_ą",
    shareResults: "ł_Add result as operational layer_ą"
});