define({
  root: {
    ok: "OK",
    cancel: "Cancel",
    exportMessage: "Export data to CSV file?",
    exportFiles: "Export to CSV",
    options: "Options",
    zoomto: "Zoom to",
    highlight: "Highlight Graphics",
    selectAll: "Select Records in All Pages",
    selectPage: "Select Records in Current Page",
    clearSelection: "Clear Selection",
    filterByExtent: "Filter by Map Extent",
    refresh: "Refresh",
    selected: "selected",
    transparent: "Transparent Mode", 
    indicate: "Locate Selection",
    columns: "Show/Hide Columns",
    selectionSymbol: "Selection Symbol",
    closeMessage: "Hide Table (expand it again from the bottom)",
    dataNotAvailable: "Data not available!<br>Click [Refresh] button to try again.",
    openTableTip: "Open Attribute Table",
    closeTableTip: "Hide Attribute Table"
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": true
});