define({
		queries:"ø_Queries_å",
		addNew: "ø_Add New_å",
		setSource: "ø_Set Source_å",
		setQuerySource: "ø_Set query source_å",
		name: "ø_Name_å",
		querySource: "ø_Query Source_å",
		queryName:"ø_Query Name_å",
		queryDefinition:"ø_Query Definition_å",
		resultsSetting:"ø_Results Setting_å",
		resultSettingTip:"ø_Define below for showing information about features that are resulted from the query operation._å",
		resultItemTitle:"ø_Result Item Title_å",
		resultItemContent:"ø_Result Item Content_å",
		fieldsSetTip:"ø_Check the fields you want to display. Select a field to change its alias,order it and format it._å",
		addField:"ø_Add Field_å",
		visibility:"ø_Visibility_å",
		alias:"ø_Alias_å",
		specialType:"ø_Special Type_å",
		actions:"ø_Actions_å",
		none:"ø_None_å",
		link:"ø_Link_å",
		image:"ø_Image_å",
		noField:"ø_No field_å",
		operationalLayerTip:"ø_Add result as operational layer_å",
		setLayerSymbolTip:"ø_Set the symbol of query result._å",
		setSelectedSymbolTip:"ø_Set the symbol of selected feature._å",
		notUseFilter:"ø_Don't use filter_å",
		setSourceTip:"ø_Please set query source !_å",
		setFilterTip:"ø_Please set filter correctly !_å",
		ok:"ø_Ok_å",
		cancel:"ø_Cancel_å"
});