define({
    taskUrl: "é_Task URL_È",
    serviceURLPlaceholder: "é_Please input Geoprocessing task URL_È",
    ok: "é_OK_È",
    cancel: "é_Cancel_È",
    layer: "é_Layer_È",
    action: "é_Action_È",
    input: "é_Input_È",
    output: "é_Output_È",
    name: "é_Name_È",
    type: "é_Type_È",
    required: "é_Required_È",
    layerOrder: "é_Layer order_È",
    options: "é_Options_È",
    defaultValue: "é_Default Value_È",
    inputFeatureBy: "é_Input Feature by_È",
    renderer: "é_Renderer_È",
    displayType: "é_Display type_È",
    label: "é_Label_È",
    tooltip: "é_Tooltip_È",
    visible: "é_Visible_È",
    helpUrl: "é_Help URL_È",
    useResultMapService: "é_Use the drawing options of result map service_È",
    drawOnMap: "é_Interactively drawing on the map_È",
    selectLayer: "é_Selecting a layer from the map_È",
    url: "é_URL_È",
    symbol: "é_Symbol_È",
    shareResults: "é_Add result as operational layer_È"
});