define({
    executeQueryTip: "한_Click one of the following items to execute query._빠",
    invalidConfig: "한_Invalid config. Please use Query setting page to get correct config._빠",
    queryParams: "한_Query Parameters_빠",
    parameters: "한_Parameters_빠",
    queries: "한_Queries_빠",
    apply: "한_Apply_빠",
    queryResults: "한_Query Results_빠",
    clear: "한_Clear_빠",
    noResults: "한_No results_빠",
    queryError: "한_Query failed !_빠",
    numberFound: "한_Number of features found_빠",
    mapExtentTip:"한_Limit the results to the current map extent._빠",
    noValue:"한_No value_빠",
    and:"한_and_빠",
    friendlyDatePattern:"한_MM/dd/yyyy_빠",
    stringOperatorIs: "한_is_빠", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "한_is not_빠",
    stringOperatorStartsWith: "한_starts with_빠",
    stringOperatorEndsWith: "한_ends with_빠",
    stringOperatorContains: "한_contains_빠",
    stringOperatorDoesNotContain: "한_does not contain_빠",
    stringOperatorIsBlank: "한_is blank_빠",
    stringOperatorIsNotBlank: "한_is not blank_빠",
    dateOperatorIsOn: "한_is on_빠", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "한_is not on_빠",
    dateOperatorIsBefore: "한_is before_빠",
    dateOperatorIsAfter: "한_is after_빠",
    dateOperatorDays: "한_days_빠",
    dateOperatorWeeks: "한_weeks_빠", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "한_months_빠",
    dateOperatorInTheLast: "한_in the last_빠",
    dateOperatorNotInTheLast: "한_not in the last_빠",
    dateOperatorIsBetween: "한_is between_빠",
    dateOperatorIsNotBetween: "한_is not between_빠",
    dateOperatorIsBlank: "한_is blank_빠",
    dateOperatorIsNotBlank: "한_is not blank_빠",
    numberOperatorIs: "한_is_빠", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "한_is not_빠",
    numberOperatorIsAtLeast: "한_is at least_빠",
    numberOperatorIsLessThan: "한_is less than_빠",
    numberOperatorIsAtMost: "한_is at most_빠",
    numberOperatorIsGreaterThan: "한_is greater than_빠",
    numberOperatorIsBetween: "한_is between_빠",
    numberOperatorIsNotBetween: "한_is not between_빠",
    numberOperatorIsBlank: "한_is blank_빠",
    numberOperatorIsNotBlank: "한_is not blank_빠"
});