define({
    ok: "Š_OK_ä",
    cancel: "Š_Cancel_ä",
    exportMessage: "Š_Export data to CSV file?_ä",
    exportFiles: "Š_Export to CSV_ä",
    options: "Š_Options_ä",
    zoomto: "Š_Zoom to_ä",
    highlight: "Š_Highlight Graphics_ä",
    selectAll: "Š_Select All Pages_ä",
    selectPage: "Š_Select Current Page_ä",
    clearSelection: "Š_Clear Selection_ä",
    filterByExtent: "Š_Filter by Map Extent_ä",
    refresh: "Š_Refresh_ä",
    selected: "Š_selected_ä",
    transparent: "Š_Transparent Mode_ä",
    indicate: "Š_Locate Selection_ä",
    columns: "Š_Show/Hide Columns_ä",
    selectionSymbol: "Š_Selection Symbol_ä",
    closeMessage: "Š_Hide table[Show it again in layer list]_ä",
    dataNotAvailable: "Š_Data not available!<br>Click [Refresh] button to have a try_ä"
});