define({
    executeQueryTip: "כן_Click one of the following items to execute query._ש",
    invalidConfig: "כן_Invalid config. Please use Query setting page to get correct config._ש",
    queryParams: "כן_Query Parameters_ש",
    parameters: "כן_Parameters_ש",
    queries: "כן_Queries_ש",
    apply: "כן_Apply_ש",
    queryResults: "כן_Query Results_ש",
    clear: "כן_Clear_ש",
    noResults: "כן_No results_ש",
    queryError: "כן_Query failed !_ש",
    numberFound: "כן_Number of features found_ש",
    mapExtentTip:"כן_Limit the results to the current map extent._ש",
    noValue:"כן_No value_ש",
    and:"כן_and_ש",
    friendlyDatePattern:"כן_MM/dd/yyyy_ש",
    stringOperatorIs: "כן_is_ש", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "כן_is not_ש",
    stringOperatorStartsWith: "כן_starts with_ש",
    stringOperatorEndsWith: "כן_ends with_ש",
    stringOperatorContains: "כן_contains_ש",
    stringOperatorDoesNotContain: "כן_does not contain_ש",
    stringOperatorIsBlank: "כן_is blank_ש",
    stringOperatorIsNotBlank: "כן_is not blank_ש",
    dateOperatorIsOn: "כן_is on_ש", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "כן_is not on_ש",
    dateOperatorIsBefore: "כן_is before_ש",
    dateOperatorIsAfter: "כן_is after_ש",
    dateOperatorDays: "כן_days_ש",
    dateOperatorWeeks: "כן_weeks_ש", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "כן_months_ש",
    dateOperatorInTheLast: "כן_in the last_ש",
    dateOperatorNotInTheLast: "כן_not in the last_ש",
    dateOperatorIsBetween: "כן_is between_ש",
    dateOperatorIsNotBetween: "כן_is not between_ש",
    dateOperatorIsBlank: "כן_is blank_ש",
    dateOperatorIsNotBlank: "כן_is not blank_ש",
    numberOperatorIs: "כן_is_ש", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "כן_is not_ש",
    numberOperatorIsAtLeast: "כן_is at least_ש",
    numberOperatorIsLessThan: "כן_is less than_ש",
    numberOperatorIsAtMost: "כן_is at most_ש",
    numberOperatorIsGreaterThan: "כן_is greater than_ש",
    numberOperatorIsBetween: "כן_is between_ש",
    numberOperatorIsNotBetween: "כן_is not between_ש",
    numberOperatorIsBlank: "כן_is blank_ש",
    numberOperatorIsNotBlank: "כן_is not blank_ש"
});