define({
    ok: "ł_OK_ą",
    cancel: "ł_Cancel_ą",
    exportMessage: "ł_Export data to CSV file?_ą",
    exportFiles: "ł_Export to CSV_ą",
    options: "ł_Options_ą",
    zoomto: "ł_Zoom to_ą",
    highlight: "ł_Highlight Graphics_ą",
    selectAll: "ł_Select All Pages_ą",
    selectPage: "ł_Select Current Page_ą",
    clearSelection: "ł_Clear Selection_ą",
    filterByExtent: "ł_Filter by Map Extent_ą",
    refresh: "ł_Refresh_ą",
    selected: "ł_selected_ą",
    transparent: "ł_Transparent Mode_ą",
    indicate: "ł_Locate Selection_ą",
    columns: "ł_Show/Hide Columns_ą",
    selectionSymbol: "ł_Selection Symbol_ą",
    closeMessage: "ł_Hide table[Show it again in layer list]_ą",
    dataNotAvailable: "ł_Data not available!<br>Click [Refresh] button to have a try_ą"
});