define({
    showArcgisBasemaps: "כן_Show ArcGIS Basemaps_ש",
    add: "כן_Click to add a new basemap_ש",
    edit: "כן_Properties_ש",
    title: "כן_Title_ש",
    thumbnail: "כן_Thumbnail_ש",
    thumbnailHint: "כן_Click image to update_ש",
    url: "כן_URL_ש",
    addlayer: "כן_Add layer_ש",
    actions: "כן_Actions_ש",
    warning: "כן_Incorrect input_ש",
    save: "כן_Back and Save_ש",
    back: "כן_Back and Cancel_ש",
    addUrl: "כן_Add URL_ש",
    autoCheck: "כן_Auto Check_ש",
    checking: "כן_Checking..._ש",
    ok: "כן_OK_ש",
    cancel: "כן_Cancel_ש",
    result: "כן_Save successfully_ש",
    spError: "כן_All basemaps added to the gallery need to have the same spatial reference._ש"
});