define({
    executeQueryTip: "ä_Click one of the following items to execute query._Ü",
    invalidConfig: "ä_Invalid config. Please use Query setting page to get correct config._Ü",
    queryParams: "ä_Query Parameters_Ü",
    parameters: "ä_Parameters_Ü",
    queries: "ä_Queries_Ü",
    apply: "ä_Apply_Ü",
    queryResults: "ä_Query Results_Ü",
    clear: "ä_Clear_Ü",
    noResults: "ä_No results_Ü",
    queryError: "ä_Query failed !_Ü",
    numberFound: "ä_Number of features found_Ü",
    mapExtentTip:"ä_Limit the results to the current map extent._Ü",
    noValue:"ä_No value_Ü",
    and:"ä_and_Ü",
    friendlyDatePattern:"ä_MM/dd/yyyy_Ü",
    stringOperatorIs: "ä_is_Ü", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "ä_is not_Ü",
    stringOperatorStartsWith: "ä_starts with_Ü",
    stringOperatorEndsWith: "ä_ends with_Ü",
    stringOperatorContains: "ä_contains_Ü",
    stringOperatorDoesNotContain: "ä_does not contain_Ü",
    stringOperatorIsBlank: "ä_is blank_Ü",
    stringOperatorIsNotBlank: "ä_is not blank_Ü",
    dateOperatorIsOn: "ä_is on_Ü", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "ä_is not on_Ü",
    dateOperatorIsBefore: "ä_is before_Ü",
    dateOperatorIsAfter: "ä_is after_Ü",
    dateOperatorDays: "ä_days_Ü",
    dateOperatorWeeks: "ä_weeks_Ü", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "ä_months_Ü",
    dateOperatorInTheLast: "ä_in the last_Ü",
    dateOperatorNotInTheLast: "ä_not in the last_Ü",
    dateOperatorIsBetween: "ä_is between_Ü",
    dateOperatorIsNotBetween: "ä_is not between_Ü",
    dateOperatorIsBlank: "ä_is blank_Ü",
    dateOperatorIsNotBlank: "ä_is not blank_Ü",
    numberOperatorIs: "ä_is_Ü", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "ä_is not_Ü",
    numberOperatorIsAtLeast: "ä_is at least_Ü",
    numberOperatorIsLessThan: "ä_is less than_Ü",
    numberOperatorIsAtMost: "ä_is at most_Ü",
    numberOperatorIsGreaterThan: "ä_is greater than_Ü",
    numberOperatorIsBetween: "ä_is between_Ü",
    numberOperatorIsNotBetween: "ä_is not between_Ü",
    numberOperatorIsBlank: "ä_is blank_Ü",
    numberOperatorIsNotBlank: "ä_is not blank_Ü"
});