define({
    showArcgisBasemaps: "Š_Show ArcGIS Basemaps_ä",
    add: "Š_Click to add a new basemap_ä",
    edit: "Š_Properties_ä",
    title: "Š_Title_ä",
    thumbnail: "Š_Thumbnail_ä",
    thumbnailHint: "Š_Click image to update_ä",
    url: "Š_URL_ä",
    addlayer: "Š_Add layer_ä",
    actions: "Š_Actions_ä",
    warning: "Š_Incorrect input_ä",
    save: "Š_Back and Save_ä",
    back: "Š_Back and Cancel_ä",
    addUrl: "Š_Add URL_ä",
    autoCheck: "Š_Auto Check_ä",
    checking: "Š_Checking..._ä",
    ok: "Š_OK_ä",
    cancel: "Š_Cancel_ä",
    result: "Š_Save successfully_ä",
    spError: "Š_All basemaps added to the gallery need to have the same spatial reference._ä"
});