define({
  root: {
    enableUndoRedo: "Enable Undo/Redo",
    toolbarVisible: "Toolbar Visible",
    toolbarOptions: "Toolbar Options",
    mergeVisible: "Merge",
    cutVisible: "Cut",
    reshapeVisible: "Reshape",
    back: "Back",
    label: "Layer",
    edit: "Editable",
    update: "Disable Update Geometry",
    fields: "Fields",
    actions: "Actions",
    editpageName: "Name",
    editpageAlias: "Alias",
    editpageVisible: "Visible",
    editpageEditable: "Editable",
    noLayers: "No editable feature layers available"
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": true
});