define({
    taskUrl: "ķ_Task URL_ū",
    serviceURLPlaceholder: "ķ_Please input Geoprocessing task URL_ū",
    ok: "ķ_OK_ū",
    cancel: "ķ_Cancel_ū",
    layer: "ķ_Layer_ū",
    action: "ķ_Action_ū",
    input: "ķ_Input_ū",
    output: "ķ_Output_ū",
    name: "ķ_Name_ū",
    type: "ķ_Type_ū",
    required: "ķ_Required_ū",
    layerOrder: "ķ_Layer order_ū",
    options: "ķ_Options_ū",
    defaultValue: "ķ_Default Value_ū",
    inputFeatureBy: "ķ_Input Feature by_ū",
    renderer: "ķ_Renderer_ū",
    displayType: "ķ_Display type_ū",
    label: "ķ_Label_ū",
    tooltip: "ķ_Tooltip_ū",
    visible: "ķ_Visible_ū",
    helpUrl: "ķ_Help URL_ū",
    useResultMapService: "ķ_Use the drawing options of result map service_ū",
    drawOnMap: "ķ_Interactively drawing on the map_ū",
    selectLayer: "ķ_Selecting a layer from the map_ū",
    url: "ķ_URL_ū",
    symbol: "ķ_Symbol_ū",
    shareResults: "ķ_Add result as operational layer_ū"
});