define({
    showArcgisBasemaps: "ã_Show ArcGIS Basemaps_Ç",
    add: "ã_Click to add a new basemap_Ç",
    edit: "ã_Properties_Ç",
    title: "ã_Title_Ç",
    thumbnail: "ã_Thumbnail_Ç",
    thumbnailHint: "ã_Click image to update_Ç",
    url: "ã_URL_Ç",
    addlayer: "ã_Add layer_Ç",
    actions: "ã_Actions_Ç",
    warning: "ã_Incorrect input_Ç",
    save: "ã_Back and Save_Ç",
    back: "ã_Back and Cancel_Ç",
    addUrl: "ã_Add URL_Ç",
    autoCheck: "ã_Auto Check_Ç",
    checking: "ã_Checking..._Ç",
    ok: "ã_OK_Ç",
    cancel: "ã_Cancel_Ç",
    result: "ã_Save successfully_Ç",
    spError: "ã_All basemaps added to the gallery need to have the same spatial reference._Ç"
});