define({
		queries:"須_Queries_鷗",
		addNew: "須_Add New_鷗",
		setSource: "須_Set Source_鷗",
		setQuerySource: "須_Set query source_鷗",
		name: "須_Name_鷗",
		querySource: "須_Query Source_鷗",
		queryName:"須_Query Name_鷗",
		queryDefinition:"須_Query Definition_鷗",
		resultsSetting:"須_Results Setting_鷗",
		resultSettingTip:"須_Define below for showing information about features that are resulted from the query operation._鷗",
		resultItemTitle:"須_Result Item Title_鷗",
		resultItemContent:"須_Result Item Content_鷗",
		fieldsSetTip:"須_Check the fields you want to display. Select a field to change its alias,order it and format it._鷗",
		addField:"須_Add Field_鷗",
		visibility:"須_Visibility_鷗",
		alias:"須_Alias_鷗",
		specialType:"須_Special Type_鷗",
		actions:"須_Actions_鷗",
		none:"須_None_鷗",
		link:"須_Link_鷗",
		image:"須_Image_鷗",
		noField:"須_No field_鷗",
		operationalLayerTip:"須_Add result as operational layer_鷗",
		setLayerSymbolTip:"須_Set the symbol of query result._鷗",
		setSelectedSymbolTip:"須_Set the symbol of selected feature._鷗",
		notUseFilter:"須_Don't use filter_鷗",
		setSourceTip:"須_Please set query source !_鷗",
		setFilterTip:"須_Please set filter correctly !_鷗",
		ok:"須_Ok_鷗",
		cancel:"須_Cancel_鷗"
});