define({
  serviceURLPlaceholder: "请输入Geoprocessing任务的URL",
  ok: "确定",
  cancel: "取消",
  layer: "图层",
  action: "操作",
  input: "输入",
  output: "输出",
  name: "名称",
  type: "类型",
  required: "必须",
  layerOrder: "图层顺序",
  options: "选项",
  defaultValue: "默认值",
  inputFeatureBy: "要素输入选项",
  renderer: "渲染器",
  displayType: "显示方式",
  label: "名称",
  tooltip: "提示信息",
  visible: "可见",
  helpUrl: "帮助链接",
  useResultMapService: "使用结果地图服务的渲染设置",
  drawOnMap: "在地图上绘制",
  selectLayer: "从图层中选择",
  url: "URL",
  symbol: "符号",
  shareResults: "将结果保存为可操作图层"
});