define({
    taskUrl: "á_Task URL_Ó",
    serviceURLPlaceholder: "á_Please input Geoprocessing task URL_Ó",
    ok: "á_OK_Ó",
    cancel: "á_Cancel_Ó",
    layer: "á_Layer_Ó",
    action: "á_Action_Ó",
    input: "á_Input_Ó",
    output: "á_Output_Ó",
    name: "á_Name_Ó",
    type: "á_Type_Ó",
    required: "á_Required_Ó",
    layerOrder: "á_Layer order_Ó",
    options: "á_Options_Ó",
    defaultValue: "á_Default Value_Ó",
    inputFeatureBy: "á_Input Feature by_Ó",
    renderer: "á_Renderer_Ó",
    displayType: "á_Display type_Ó",
    label: "á_Label_Ó",
    tooltip: "á_Tooltip_Ó",
    visible: "á_Visible_Ó",
    helpUrl: "á_Help URL_Ó",
    useResultMapService: "á_Use the drawing options of result map service_Ó",
    drawOnMap: "á_Interactively drawing on the map_Ó",
    selectLayer: "á_Selecting a layer from the map_Ó",
    url: "á_URL_Ó",
    symbol: "á_Symbol_Ó",
    shareResults: "á_Add result as operational layer_Ó"
});