define({
    executeQueryTip: "Ă_Click one of the following items to execute query._ș",
    invalidConfig: "Ă_Invalid config. Please use Query setting page to get correct config._ș",
    queryParams: "Ă_Query Parameters_ș",
    parameters: "Ă_Parameters_ș",
    queries: "Ă_Queries_ș",
    apply: "Ă_Apply_ș",
    queryResults: "Ă_Query Results_ș",
    clear: "Ă_Clear_ș",
    noResults: "Ă_No results_ș",
    queryError: "Ă_Query failed !_ș",
    numberFound: "Ă_Number of features found_ș",
    mapExtentTip:"Ă_Limit the results to the current map extent._ș",
    noValue:"Ă_No value_ș",
    and:"Ă_and_ș",
    friendlyDatePattern:"Ă_MM/dd/yyyy_ș",
    stringOperatorIs: "Ă_is_ș", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "Ă_is not_ș",
    stringOperatorStartsWith: "Ă_starts with_ș",
    stringOperatorEndsWith: "Ă_ends with_ș",
    stringOperatorContains: "Ă_contains_ș",
    stringOperatorDoesNotContain: "Ă_does not contain_ș",
    stringOperatorIsBlank: "Ă_is blank_ș",
    stringOperatorIsNotBlank: "Ă_is not blank_ș",
    dateOperatorIsOn: "Ă_is on_ș", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "Ă_is not on_ș",
    dateOperatorIsBefore: "Ă_is before_ș",
    dateOperatorIsAfter: "Ă_is after_ș",
    dateOperatorDays: "Ă_days_ș",
    dateOperatorWeeks: "Ă_weeks_ș", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "Ă_months_ș",
    dateOperatorInTheLast: "Ă_in the last_ș",
    dateOperatorNotInTheLast: "Ă_not in the last_ș",
    dateOperatorIsBetween: "Ă_is between_ș",
    dateOperatorIsNotBetween: "Ă_is not between_ș",
    dateOperatorIsBlank: "Ă_is blank_ș",
    dateOperatorIsNotBlank: "Ă_is not blank_ș",
    numberOperatorIs: "Ă_is_ș", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "Ă_is not_ș",
    numberOperatorIsAtLeast: "Ă_is at least_ș",
    numberOperatorIsLessThan: "Ă_is less than_ș",
    numberOperatorIsAtMost: "Ă_is at most_ș",
    numberOperatorIsGreaterThan: "Ă_is greater than_ș",
    numberOperatorIsBetween: "Ă_is between_ș",
    numberOperatorIsNotBetween: "Ă_is not between_ș",
    numberOperatorIsBlank: "Ă_is blank_ș",
    numberOperatorIsNotBlank: "Ă_is not blank_ș"
});