define({
    executeQueryTip: "Ř_Click one of the following items to execute query._ů",
    invalidConfig: "Ř_Invalid config. Please use Query setting page to get correct config._ů",
    queryParams: "Ř_Query Parameters_ů",
    parameters: "Ř_Parameters_ů",
    queries: "Ř_Queries_ů",
    apply: "Ř_Apply_ů",
    queryResults: "Ř_Query Results_ů",
    clear: "Ř_Clear_ů",
    noResults: "Ř_No results_ů",
    queryError: "Ř_Query failed !_ů",
    numberFound: "Ř_Number of features found_ů",
    mapExtentTip:"Ř_Limit the results to the current map extent._ů",
    noValue:"Ř_No value_ů",
    and:"Ř_and_ů",
    friendlyDatePattern:"Ř_MM/dd/yyyy_ů",
    stringOperatorIs: "Ř_is_ů", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "Ř_is not_ů",
    stringOperatorStartsWith: "Ř_starts with_ů",
    stringOperatorEndsWith: "Ř_ends with_ů",
    stringOperatorContains: "Ř_contains_ů",
    stringOperatorDoesNotContain: "Ř_does not contain_ů",
    stringOperatorIsBlank: "Ř_is blank_ů",
    stringOperatorIsNotBlank: "Ř_is not blank_ů",
    dateOperatorIsOn: "Ř_is on_ů", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "Ř_is not on_ů",
    dateOperatorIsBefore: "Ř_is before_ů",
    dateOperatorIsAfter: "Ř_is after_ů",
    dateOperatorDays: "Ř_days_ů",
    dateOperatorWeeks: "Ř_weeks_ů", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "Ř_months_ů",
    dateOperatorInTheLast: "Ř_in the last_ů",
    dateOperatorNotInTheLast: "Ř_not in the last_ů",
    dateOperatorIsBetween: "Ř_is between_ů",
    dateOperatorIsNotBetween: "Ř_is not between_ů",
    dateOperatorIsBlank: "Ř_is blank_ů",
    dateOperatorIsNotBlank: "Ř_is not blank_ů",
    numberOperatorIs: "Ř_is_ů", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "Ř_is not_ů",
    numberOperatorIsAtLeast: "Ř_is at least_ů",
    numberOperatorIsLessThan: "Ř_is less than_ů",
    numberOperatorIsAtMost: "Ř_is at most_ů",
    numberOperatorIsGreaterThan: "Ř_is greater than_ů",
    numberOperatorIsBetween: "Ř_is between_ů",
    numberOperatorIsNotBetween: "Ř_is not between_ů",
    numberOperatorIsBlank: "Ř_is blank_ů",
    numberOperatorIsNotBlank: "Ř_is not blank_ů"
});