define({
    ok: "Ă_OK_ș",
    cancel: "Ă_Cancel_ș",
    exportMessage: "Ă_Export data to CSV file?_ș",
    exportFiles: "Ă_Export to CSV_ș",
    options: "Ă_Options_ș",
    zoomto: "Ă_Zoom to_ș",
    highlight: "Ă_Highlight Graphics_ș",
    selectAll: "Ă_Select All Pages_ș",
    selectPage: "Ă_Select Current Page_ș",
    clearSelection: "Ă_Clear Selection_ș",
    filterByExtent: "Ă_Filter by Map Extent_ș",
    refresh: "Ă_Refresh_ș",
    selected: "Ă_selected_ș",
    transparent: "Ă_Transparent Mode_ș",
    indicate: "Ă_Locate Selection_ș",
    columns: "Ă_Show/Hide Columns_ș",
    selectionSymbol: "Ă_Selection Symbol_ș",
    closeMessage: "Ă_Hide table[Show it again in layer list]_ș",
    dataNotAvailable: "Ă_Data not available!<br>Click [Refresh] button to have a try_ș"
});