define({
    taskUrl: "ø_Task URL_å",
    serviceURLPlaceholder: "ø_Please input Geoprocessing task URL_å",
    ok: "ø_OK_å",
    cancel: "ø_Cancel_å",
    layer: "ø_Layer_å",
    action: "ø_Action_å",
    input: "ø_Input_å",
    output: "ø_Output_å",
    name: "ø_Name_å",
    type: "ø_Type_å",
    required: "ø_Required_å",
    layerOrder: "ø_Layer order_å",
    options: "ø_Options_å",
    defaultValue: "ø_Default Value_å",
    inputFeatureBy: "ø_Input Feature by_å",
    renderer: "ø_Renderer_å",
    displayType: "ø_Display type_å",
    label: "ø_Label_å",
    tooltip: "ø_Tooltip_å",
    visible: "ø_Visible_å",
    helpUrl: "ø_Help URL_å",
    useResultMapService: "ø_Use the drawing options of result map service_å",
    drawOnMap: "ø_Interactively drawing on the map_å",
    selectLayer: "ø_Selecting a layer from the map_å",
    url: "ø_URL_å",
    symbol: "ø_Symbol_å",
    shareResults: "ø_Add result as operational layer_å"
});