define({
  root: {
    showArcgisBasemaps: "Include Portal's basemaps",
    settings: "Settings",
    add: "Click to add a new basemap",
    edit: "Properties",
    title: "Title",
    thumbnail: "Thumbnail",
    thumbnailHint: "Click image to update",
    url: "URL",
    addlayer: "Add Sublayer",
    actions: "Actions",
    warning: "Incorrect input",
    save: "Back and Save",
    back: "Back and Cancel",
    addUrl: "Add URL",
    autoCheck: "Auto Check",
    checking: "Checking...",
    ok: "OK",
    cancel: "Cancel",
    result: "Save successfully",
    spError: "All basemaps added to the gallery need to have the same spatial reference."
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": true
});