define({
    taskUrl: "Ř_Task URL_ů",
    serviceURLPlaceholder: "Ř_Please input Geoprocessing task URL_ů",
    ok: "Ř_OK_ů",
    cancel: "Ř_Cancel_ů",
    layer: "Ř_Layer_ů",
    action: "Ř_Action_ů",
    input: "Ř_Input_ů",
    output: "Ř_Output_ů",
    name: "Ř_Name_ů",
    type: "Ř_Type_ů",
    required: "Ř_Required_ů",
    layerOrder: "Ř_Layer order_ů",
    options: "Ř_Options_ů",
    defaultValue: "Ř_Default Value_ů",
    inputFeatureBy: "Ř_Input Feature by_ů",
    renderer: "Ř_Renderer_ů",
    displayType: "Ř_Display type_ů",
    label: "Ř_Label_ů",
    tooltip: "Ř_Tooltip_ů",
    visible: "Ř_Visible_ů",
    helpUrl: "Ř_Help URL_ů",
    useResultMapService: "Ř_Use the drawing options of result map service_ů",
    drawOnMap: "Ř_Interactively drawing on the map_ů",
    selectLayer: "Ř_Selecting a layer from the map_ů",
    url: "Ř_URL_ů",
    symbol: "Ř_Symbol_ů",
    shareResults: "Ř_Add result as operational layer_ů"
});