define({
    ok: "å_OK_ø",
    cancel: "å_Cancel_ø",
    exportMessage: "å_Export data to CSV file?_ø",
    exportFiles: "å_Export to CSV_ø",
    options: "å_Options_ø",
    zoomto: "å_Zoom to_ø",
    highlight: "å_Highlight Graphics_ø",
    selectAll: "å_Select All Pages_ø",
    selectPage: "å_Select Current Page_ø",
    clearSelection: "å_Clear Selection_ø",
    filterByExtent: "å_Filter by Map Extent_ø",
    refresh: "å_Refresh_ø",
    selected: "å_selected_ø",
    transparent: "å_Transparent Mode_ø",
    indicate: "å_Locate Selection_ø",
    columns: "å_Show/Hide Columns_ø",
    selectionSymbol: "å_Selection Symbol_ø",
    closeMessage: "å_Hide table[Show it again in layer list]_ø",
    dataNotAvailable: "å_Data not available!<br>Click [Refresh] button to have a try_ø"
});