define({
		queries:"查询任务",
		addNew: "新建",
		setSource: "设置",
		setQuerySource: "设置查询数据源",
		name: "名称",
		querySource: "数据源",
		queryName:"任务名称",
		queryDefinition:"查询条件定义",
		resultsSetting:"结果设置",
		symbolSetting:"符号设置",
		resultSettingTip:"为查询得到的要素定义显示信息。",
		resultItemTitle:"结果条目标题",
		resultItemContent:"结果条目内容",
		fieldsSetTip:"选择用于显示的字段。更改字段的别名、顺序和格式。",
		addField:"添加字段",
		visibility:"可见性",
		alias:"别名",
		specialType:"特殊类型",
		actions:"操作",
		none:"无",
		link:"链接",
		image:"图像",
		noField:"没有字段",
		operationalLayerTip:"将结果添加为业务图层",
		setLayerSymbolTip:"为查询得到的要素设置符号： ",
		setSelectedSymbolTip:"Set symbol of selected feature.",
		notUseFilter:"不适用过滤器",
		setSourceTip:"请设置查询数据源!",
		setFilterTip:"请正确设置空间过滤范围!",
		ok:"确定",
		cancel:"取消"
});