define({
    showArcgisBasemaps: "æ_Show ArcGIS Basemaps_Â",
    add: "æ_Click to add a new basemap_Â",
    edit: "æ_Properties_Â",
    title: "æ_Title_Â",
    thumbnail: "æ_Thumbnail_Â",
    thumbnailHint: "æ_Click image to update_Â",
    url: "æ_URL_Â",
    addlayer: "æ_Add layer_Â",
    actions: "æ_Actions_Â",
    warning: "æ_Incorrect input_Â",
    save: "æ_Back and Save_Â",
    back: "æ_Back and Cancel_Â",
    addUrl: "æ_Add URL_Â",
    autoCheck: "æ_Auto Check_Â",
    checking: "æ_Checking..._Â",
    ok: "æ_OK_Â",
    cancel: "æ_Cancel_Â",
    result: "æ_Save successfully_Â",
    spError: "æ_All basemaps added to the gallery need to have the same spatial reference._Â"
});