define({
		queries:"Ж_Queries_Я",
		addNew: "Ж_Add New_Я",
		setSource: "Ж_Set Source_Я",
		setQuerySource: "Ж_Set query source_Я",
		name: "Ж_Name_Я",
		querySource: "Ж_Query Source_Я",
		queryName:"Ж_Query Name_Я",
		queryDefinition:"Ж_Query Definition_Я",
		resultsSetting:"Ж_Results Setting_Я",
		resultSettingTip:"Ж_Define below for showing information about features that are resulted from the query operation._Я",
		resultItemTitle:"Ж_Result Item Title_Я",
		resultItemContent:"Ж_Result Item Content_Я",
		fieldsSetTip:"Ж_Check the fields you want to display. Select a field to change its alias,order it and format it._Я",
		addField:"Ж_Add Field_Я",
		visibility:"Ж_Visibility_Я",
		alias:"Ж_Alias_Я",
		specialType:"Ж_Special Type_Я",
		actions:"Ж_Actions_Я",
		none:"Ж_None_Я",
		link:"Ж_Link_Я",
		image:"Ж_Image_Я",
		noField:"Ж_No field_Я",
		operationalLayerTip:"Ж_Add result as operational layer_Я",
		setLayerSymbolTip:"Ж_Set the symbol of query result._Я",
		setSelectedSymbolTip:"Ж_Set the symbol of selected feature._Я",
		notUseFilter:"Ж_Don't use filter_Я",
		setSourceTip:"Ж_Please set query source !_Я",
		setFilterTip:"Ж_Please set filter correctly !_Я",
		ok:"Ж_Ok_Я",
		cancel:"Ж_Cancel_Я"
});