define({
		queries:"ł_Queries_ą",
		addNew: "ł_Add New_ą",
		setSource: "ł_Set Source_ą",
		setQuerySource: "ł_Set query source_ą",
		name: "ł_Name_ą",
		querySource: "ł_Query Source_ą",
		queryName:"ł_Query Name_ą",
		queryDefinition:"ł_Query Definition_ą",
		resultsSetting:"ł_Results Setting_ą",
		resultSettingTip:"ł_Define below for showing information about features that are resulted from the query operation._ą",
		resultItemTitle:"ł_Result Item Title_ą",
		resultItemContent:"ł_Result Item Content_ą",
		fieldsSetTip:"ł_Check the fields you want to display. Select a field to change its alias,order it and format it._ą",
		addField:"ł_Add Field_ą",
		visibility:"ł_Visibility_ą",
		alias:"ł_Alias_ą",
		specialType:"ł_Special Type_ą",
		actions:"ł_Actions_ą",
		none:"ł_None_ą",
		link:"ł_Link_ą",
		image:"ł_Image_ą",
		noField:"ł_No field_ą",
		operationalLayerTip:"ł_Add result as operational layer_ą",
		setLayerSymbolTip:"ł_Set the symbol of query result._ą",
		setSelectedSymbolTip:"ł_Set the symbol of selected feature._ą",
		notUseFilter:"ł_Don't use filter_ą",
		setSourceTip:"ł_Please set query source !_ą",
		setFilterTip:"ł_Please set filter correctly !_ą",
		ok:"ł_Ok_ą",
		cancel:"ł_Cancel_ą"
});