define({
		queries:"á_Queries_Ó",
		addNew: "á_Add New_Ó",
		setSource: "á_Set Source_Ó",
		setQuerySource: "á_Set query source_Ó",
		name: "á_Name_Ó",
		querySource: "á_Query Source_Ó",
		queryName:"á_Query Name_Ó",
		queryDefinition:"á_Query Definition_Ó",
		resultsSetting:"á_Results Setting_Ó",
		resultSettingTip:"á_Define below for showing information about features that are resulted from the query operation._Ó",
		resultItemTitle:"á_Result Item Title_Ó",
		resultItemContent:"á_Result Item Content_Ó",
		fieldsSetTip:"á_Check the fields you want to display. Select a field to change its alias,order it and format it._Ó",
		addField:"á_Add Field_Ó",
		visibility:"á_Visibility_Ó",
		alias:"á_Alias_Ó",
		specialType:"á_Special Type_Ó",
		actions:"á_Actions_Ó",
		none:"á_None_Ó",
		link:"á_Link_Ó",
		image:"á_Image_Ó",
		noField:"á_No field_Ó",
		operationalLayerTip:"á_Add result as operational layer_Ó",
		setLayerSymbolTip:"á_Set the symbol of query result._Ó",
		setSelectedSymbolTip:"á_Set the symbol of selected feature._Ó",
		notUseFilter:"á_Don't use filter_Ó",
		setSourceTip:"á_Please set query source !_Ó",
		setFilterTip:"á_Please set filter correctly !_Ó",
		ok:"á_Ok_Ó",
		cancel:"á_Cancel_Ó"
});