define({
		queries:"ķ_Queries_ū",
		addNew: "ķ_Add New_ū",
		setSource: "ķ_Set Source_ū",
		setQuerySource: "ķ_Set query source_ū",
		name: "ķ_Name_ū",
		querySource: "ķ_Query Source_ū",
		queryName:"ķ_Query Name_ū",
		queryDefinition:"ķ_Query Definition_ū",
		resultsSetting:"ķ_Results Setting_ū",
		resultSettingTip:"ķ_Define below for showing information about features that are resulted from the query operation._ū",
		resultItemTitle:"ķ_Result Item Title_ū",
		resultItemContent:"ķ_Result Item Content_ū",
		fieldsSetTip:"ķ_Check the fields you want to display. Select a field to change its alias,order it and format it._ū",
		addField:"ķ_Add Field_ū",
		visibility:"ķ_Visibility_ū",
		alias:"ķ_Alias_ū",
		specialType:"ķ_Special Type_ū",
		actions:"ķ_Actions_ū",
		none:"ķ_None_ū",
		link:"ķ_Link_ū",
		image:"ķ_Image_ū",
		noField:"ķ_No field_ū",
		operationalLayerTip:"ķ_Add result as operational layer_ū",
		setLayerSymbolTip:"ķ_Set the symbol of query result._ū",
		setSelectedSymbolTip:"ķ_Set the symbol of selected feature._ū",
		notUseFilter:"ķ_Don't use filter_ū",
		setSourceTip:"ķ_Please set query source !_ū",
		setFilterTip:"ķ_Please set filter correctly !_ū",
		ok:"ķ_Ok_ū",
		cancel:"ķ_Cancel_ū"
});