define({
		queries:"ı_Queries_İ",
		addNew: "ı_Add New_İ",
		setSource: "ı_Set Source_İ",
		setQuerySource: "ı_Set query source_İ",
		name: "ı_Name_İ",
		querySource: "ı_Query Source_İ",
		queryName:"ı_Query Name_İ",
		queryDefinition:"ı_Query Definition_İ",
		resultsSetting:"ı_Results Setting_İ",
		resultSettingTip:"ı_Define below for showing information about features that are resulted from the query operation._İ",
		resultItemTitle:"ı_Result Item Title_İ",
		resultItemContent:"ı_Result Item Content_İ",
		fieldsSetTip:"ı_Check the fields you want to display. Select a field to change its alias,order it and format it._İ",
		addField:"ı_Add Field_İ",
		visibility:"ı_Visibility_İ",
		alias:"ı_Alias_İ",
		specialType:"ı_Special Type_İ",
		actions:"ı_Actions_İ",
		none:"ı_None_İ",
		link:"ı_Link_İ",
		image:"ı_Image_İ",
		noField:"ı_No field_İ",
		operationalLayerTip:"ı_Add result as operational layer_İ",
		setLayerSymbolTip:"ı_Set the symbol of query result._İ",
		setSelectedSymbolTip:"ı_Set the symbol of selected feature._İ",
		notUseFilter:"ı_Don't use filter_İ",
		setSourceTip:"ı_Please set query source !_İ",
		setFilterTip:"ı_Please set filter correctly !_İ",
		ok:"ı_Ok_İ",
		cancel:"ı_Cancel_İ"
});