define({
    executeQueryTip: "Ĳ_Click one of the following items to execute query._ä",
    invalidConfig: "Ĳ_Invalid config. Please use Query setting page to get correct config._ä",
    queryParams: "Ĳ_Query Parameters_ä",
    parameters: "Ĳ_Parameters_ä",
    queries: "Ĳ_Queries_ä",
    apply: "Ĳ_Apply_ä",
    queryResults: "Ĳ_Query Results_ä",
    clear: "Ĳ_Clear_ä",
    noResults: "Ĳ_No results_ä",
    queryError: "Ĳ_Query failed !_ä",
    numberFound: "Ĳ_Number of features found_ä",
    mapExtentTip:"Ĳ_Limit the results to the current map extent._ä",
    noValue:"Ĳ_No value_ä",
    and:"Ĳ_and_ä",
    friendlyDatePattern:"Ĳ_MM/dd/yyyy_ä",
    stringOperatorIs: "Ĳ_is_ä", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "Ĳ_is not_ä",
    stringOperatorStartsWith: "Ĳ_starts with_ä",
    stringOperatorEndsWith: "Ĳ_ends with_ä",
    stringOperatorContains: "Ĳ_contains_ä",
    stringOperatorDoesNotContain: "Ĳ_does not contain_ä",
    stringOperatorIsBlank: "Ĳ_is blank_ä",
    stringOperatorIsNotBlank: "Ĳ_is not blank_ä",
    dateOperatorIsOn: "Ĳ_is on_ä", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "Ĳ_is not on_ä",
    dateOperatorIsBefore: "Ĳ_is before_ä",
    dateOperatorIsAfter: "Ĳ_is after_ä",
    dateOperatorDays: "Ĳ_days_ä",
    dateOperatorWeeks: "Ĳ_weeks_ä", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "Ĳ_months_ä",
    dateOperatorInTheLast: "Ĳ_in the last_ä",
    dateOperatorNotInTheLast: "Ĳ_not in the last_ä",
    dateOperatorIsBetween: "Ĳ_is between_ä",
    dateOperatorIsNotBetween: "Ĳ_is not between_ä",
    dateOperatorIsBlank: "Ĳ_is blank_ä",
    dateOperatorIsNotBlank: "Ĳ_is not blank_ä",
    numberOperatorIs: "Ĳ_is_ä", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "Ĳ_is not_ä",
    numberOperatorIsAtLeast: "Ĳ_is at least_ä",
    numberOperatorIsLessThan: "Ĳ_is less than_ä",
    numberOperatorIsAtMost: "Ĳ_is at most_ä",
    numberOperatorIsGreaterThan: "Ĳ_is greater than_ä",
    numberOperatorIsBetween: "Ĳ_is between_ä",
    numberOperatorIsNotBetween: "Ĳ_is not between_ä",
    numberOperatorIsBlank: "Ĳ_is blank_ä",
    numberOperatorIsNotBlank: "Ĳ_is not blank_ä"
});