define({
    ok: "ø_OK_å",
    cancel: "ø_Cancel_å",
    exportMessage: "ø_Export data to CSV file?_å",
    exportFiles: "ø_Export to CSV_å",
    options: "ø_Options_å",
    zoomto: "ø_Zoom to_å",
    highlight: "ø_Highlight Graphics_å",
    selectAll: "ø_Select All Pages_å",
    selectPage: "ø_Select Current Page_å",
    clearSelection: "ø_Clear Selection_å",
    filterByExtent: "ø_Filter by Map Extent_å",
    refresh: "ø_Refresh_å",
    selected: "ø_selected_å",
    transparent: "ø_Transparent Mode_å",
    indicate: "ø_Locate Selection_å",
    columns: "ø_Show/Hide Columns_å",
    selectionSymbol: "ø_Selection Symbol_å",
    closeMessage: "ø_Hide table[Show it again in layer list]_å",
    dataNotAvailable: "ø_Data not available!<br>Click [Refresh] button to have a try_å"
});