define({
    ok: "ก้_OK_ษฺ",
    cancel: "ก้_Cancel_ษฺ",
    exportMessage: "ก้_Export data to CSV file?_ษฺ",
    exportFiles: "ก้_Export to CSV_ษฺ",
    options: "ก้_Options_ษฺ",
    zoomto: "ก้_Zoom to_ษฺ",
    highlight: "ก้_Highlight Graphics_ษฺ",
    selectAll: "ก้_Select All Pages_ษฺ",
    selectPage: "ก้_Select Current Page_ษฺ",
    clearSelection: "ก้_Clear Selection_ษฺ",
    filterByExtent: "ก้_Filter by Map Extent_ษฺ",
    refresh: "ก้_Refresh_ษฺ",
    selected: "ก้_selected_ษฺ",
    transparent: "ก้_Transparent Mode_ษฺ",
    indicate: "ก้_Locate Selection_ษฺ",
    columns: "ก้_Show/Hide Columns_ษฺ",
    selectionSymbol: "ก้_Selection Symbol_ษฺ",
    closeMessage: "ก้_Hide table[Show it again in layer list]_ษฺ",
    dataNotAvailable: "ก้_Data not available!<br>Click [Refresh] button to have a try_ษฺ"
});