define({
		queries:"æ_Queries_Â",
		addNew: "æ_Add New_Â",
		setSource: "æ_Set Source_Â",
		setQuerySource: "æ_Set query source_Â",
		name: "æ_Name_Â",
		querySource: "æ_Query Source_Â",
		queryName:"æ_Query Name_Â",
		queryDefinition:"æ_Query Definition_Â",
		resultsSetting:"æ_Results Setting_Â",
		resultSettingTip:"æ_Define below for showing information about features that are resulted from the query operation._Â",
		resultItemTitle:"æ_Result Item Title_Â",
		resultItemContent:"æ_Result Item Content_Â",
		fieldsSetTip:"æ_Check the fields you want to display. Select a field to change its alias,order it and format it._Â",
		addField:"æ_Add Field_Â",
		visibility:"æ_Visibility_Â",
		alias:"æ_Alias_Â",
		specialType:"æ_Special Type_Â",
		actions:"æ_Actions_Â",
		none:"æ_None_Â",
		link:"æ_Link_Â",
		image:"æ_Image_Â",
		noField:"æ_No field_Â",
		operationalLayerTip:"æ_Add result as operational layer_Â",
		setLayerSymbolTip:"æ_Set the symbol of query result._Â",
		setSelectedSymbolTip:"æ_Set the symbol of selected feature._Â",
		notUseFilter:"æ_Don't use filter_Â",
		setSourceTip:"æ_Please set query source !_Â",
		setFilterTip:"æ_Please set filter correctly !_Â",
		ok:"æ_Ok_Â",
		cancel:"æ_Cancel_Â"
});