define({
		queries:"כן_Queries_ש",
		addNew: "כן_Add New_ש",
		setSource: "כן_Set Source_ש",
		setQuerySource: "כן_Set query source_ש",
		name: "כן_Name_ש",
		querySource: "כן_Query Source_ש",
		queryName:"כן_Query Name_ש",
		queryDefinition:"כן_Query Definition_ש",
		resultsSetting:"כן_Results Setting_ש",
		resultSettingTip:"כן_Define below for showing information about features that are resulted from the query operation._ש",
		resultItemTitle:"כן_Result Item Title_ש",
		resultItemContent:"כן_Result Item Content_ש",
		fieldsSetTip:"כן_Check the fields you want to display. Select a field to change its alias,order it and format it._ש",
		addField:"כן_Add Field_ש",
		visibility:"כן_Visibility_ש",
		alias:"כן_Alias_ש",
		specialType:"כן_Special Type_ש",
		actions:"כן_Actions_ש",
		none:"כן_None_ש",
		link:"כן_Link_ש",
		image:"כן_Image_ש",
		noField:"כן_No field_ש",
		operationalLayerTip:"כן_Add result as operational layer_ש",
		setLayerSymbolTip:"כן_Set the symbol of query result._ש",
		setSelectedSymbolTip:"כן_Set the symbol of selected feature._ש",
		notUseFilter:"כן_Don't use filter_ש",
		setSourceTip:"כן_Please set query source !_ש",
		setFilterTip:"כן_Please set filter correctly !_ש",
		ok:"כן_Ok_ש",
		cancel:"כן_Cancel_ש"
});