define({
    showArcgisBasemaps: "á_Show ArcGIS Basemaps_Ó",
    add: "á_Click to add a new basemap_Ó",
    edit: "á_Properties_Ó",
    title: "á_Title_Ó",
    thumbnail: "á_Thumbnail_Ó",
    thumbnailHint: "á_Click image to update_Ó",
    url: "á_URL_Ó",
    addlayer: "á_Add layer_Ó",
    actions: "á_Actions_Ó",
    warning: "á_Incorrect input_Ó",
    save: "á_Back and Save_Ó",
    back: "á_Back and Cancel_Ó",
    addUrl: "á_Add URL_Ó",
    autoCheck: "á_Auto Check_Ó",
    checking: "á_Checking..._Ó",
    ok: "á_OK_Ó",
    cancel: "á_Cancel_Ó",
    result: "á_Save successfully_Ó",
    spError: "á_All basemaps added to the gallery need to have the same spatial reference._Ó"
});