define({
    executeQueryTip: "ก้_Click one of the following items to execute query._ษฺ",
    invalidConfig: "ก้_Invalid config. Please use Query setting page to get correct config._ษฺ",
    queryParams: "ก้_Query Parameters_ษฺ",
    parameters: "ก้_Parameters_ษฺ",
    queries: "ก้_Queries_ษฺ",
    apply: "ก้_Apply_ษฺ",
    queryResults: "ก้_Query Results_ษฺ",
    clear: "ก้_Clear_ษฺ",
    noResults: "ก้_No results_ษฺ",
    queryError: "ก้_Query failed !_ษฺ",
    numberFound: "ก้_Number of features found_ษฺ",
    mapExtentTip:"ก้_Limit the results to the current map extent._ษฺ",
    noValue:"ก้_No value_ษฺ",
    and:"ก้_and_ษฺ",
    friendlyDatePattern:"ก้_MM/dd/yyyy_ษฺ",
    stringOperatorIs: "ก้_is_ษฺ", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "ก้_is not_ษฺ",
    stringOperatorStartsWith: "ก้_starts with_ษฺ",
    stringOperatorEndsWith: "ก้_ends with_ษฺ",
    stringOperatorContains: "ก้_contains_ษฺ",
    stringOperatorDoesNotContain: "ก้_does not contain_ษฺ",
    stringOperatorIsBlank: "ก้_is blank_ษฺ",
    stringOperatorIsNotBlank: "ก้_is not blank_ษฺ",
    dateOperatorIsOn: "ก้_is on_ษฺ", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "ก้_is not on_ษฺ",
    dateOperatorIsBefore: "ก้_is before_ษฺ",
    dateOperatorIsAfter: "ก้_is after_ษฺ",
    dateOperatorDays: "ก้_days_ษฺ",
    dateOperatorWeeks: "ก้_weeks_ษฺ", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "ก้_months_ษฺ",
    dateOperatorInTheLast: "ก้_in the last_ษฺ",
    dateOperatorNotInTheLast: "ก้_not in the last_ษฺ",
    dateOperatorIsBetween: "ก้_is between_ษฺ",
    dateOperatorIsNotBetween: "ก้_is not between_ษฺ",
    dateOperatorIsBlank: "ก้_is blank_ษฺ",
    dateOperatorIsNotBlank: "ก้_is not blank_ษฺ",
    numberOperatorIs: "ก้_is_ษฺ", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "ก้_is not_ษฺ",
    numberOperatorIsAtLeast: "ก้_is at least_ษฺ",
    numberOperatorIsLessThan: "ก้_is less than_ษฺ",
    numberOperatorIsAtMost: "ก้_is at most_ษฺ",
    numberOperatorIsGreaterThan: "ก้_is greater than_ษฺ",
    numberOperatorIsBetween: "ก้_is between_ษฺ",
    numberOperatorIsNotBetween: "ก้_is not between_ษฺ",
    numberOperatorIsBlank: "ก้_is blank_ษฺ",
    numberOperatorIsNotBlank: "ก้_is not blank_ษฺ"
});