define({
    showArcgisBasemaps: "Å_Show ArcGIS Basemaps_ö",
    add: "Å_Click to add a new basemap_ö",
    edit: "Å_Properties_ö",
    title: "Å_Title_ö",
    thumbnail: "Å_Thumbnail_ö",
    thumbnailHint: "Å_Click image to update_ö",
    url: "Å_URL_ö",
    addlayer: "Å_Add layer_ö",
    actions: "Å_Actions_ö",
    warning: "Å_Incorrect input_ö",
    save: "Å_Back and Save_ö",
    back: "Å_Back and Cancel_ö",
    addUrl: "Å_Add URL_ö",
    autoCheck: "Å_Auto Check_ö",
    checking: "Å_Checking..._ö",
    ok: "Å_OK_ö",
    cancel: "Å_Cancel_ö",
    result: "Å_Save successfully_ö",
    spError: "Å_All basemaps added to the gallery need to have the same spatial reference._ö"
});