define({
		queries:"Š_Queries_ä",
		addNew: "Š_Add New_ä",
		setSource: "Š_Set Source_ä",
		setQuerySource: "Š_Set query source_ä",
		name: "Š_Name_ä",
		querySource: "Š_Query Source_ä",
		queryName:"Š_Query Name_ä",
		queryDefinition:"Š_Query Definition_ä",
		resultsSetting:"Š_Results Setting_ä",
		resultSettingTip:"Š_Define below for showing information about features that are resulted from the query operation._ä",
		resultItemTitle:"Š_Result Item Title_ä",
		resultItemContent:"Š_Result Item Content_ä",
		fieldsSetTip:"Š_Check the fields you want to display. Select a field to change its alias,order it and format it._ä",
		addField:"Š_Add Field_ä",
		visibility:"Š_Visibility_ä",
		alias:"Š_Alias_ä",
		specialType:"Š_Special Type_ä",
		actions:"Š_Actions_ä",
		none:"Š_None_ä",
		link:"Š_Link_ä",
		image:"Š_Image_ä",
		noField:"Š_No field_ä",
		operationalLayerTip:"Š_Add result as operational layer_ä",
		setLayerSymbolTip:"Š_Set the symbol of query result._ä",
		setSelectedSymbolTip:"Š_Set the symbol of selected feature._ä",
		notUseFilter:"Š_Don't use filter_ä",
		setSourceTip:"Š_Please set query source !_ä",
		setFilterTip:"Š_Please set filter correctly !_ä",
		ok:"Š_Ok_ä",
		cancel:"Š_Cancel_ä"
});