define({
    executeQueryTip: "é_Click one of the following items to execute query._È",
    invalidConfig: "é_Invalid config. Please use Query setting page to get correct config._È",
    queryParams: "é_Query Parameters_È",
    parameters: "é_Parameters_È",
    queries: "é_Queries_È",
    apply: "é_Apply_È",
    queryResults: "é_Query Results_È",
    clear: "é_Clear_È",
    noResults: "é_No results_È",
    queryError: "é_Query failed !_È",
    numberFound: "é_Number of features found_È",
    mapExtentTip:"é_Limit the results to the current map extent._È",
    noValue:"é_No value_È",
    and:"é_and_È",
    friendlyDatePattern:"é_MM/dd/yyyy_È",
    stringOperatorIs: "é_is_È", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "é_is not_È",
    stringOperatorStartsWith: "é_starts with_È",
    stringOperatorEndsWith: "é_ends with_È",
    stringOperatorContains: "é_contains_È",
    stringOperatorDoesNotContain: "é_does not contain_È",
    stringOperatorIsBlank: "é_is blank_È",
    stringOperatorIsNotBlank: "é_is not blank_È",
    dateOperatorIsOn: "é_is on_È", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "é_is not on_È",
    dateOperatorIsBefore: "é_is before_È",
    dateOperatorIsAfter: "é_is after_È",
    dateOperatorDays: "é_days_È",
    dateOperatorWeeks: "é_weeks_È", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "é_months_È",
    dateOperatorInTheLast: "é_in the last_È",
    dateOperatorNotInTheLast: "é_not in the last_È",
    dateOperatorIsBetween: "é_is between_È",
    dateOperatorIsNotBetween: "é_is not between_È",
    dateOperatorIsBlank: "é_is blank_È",
    dateOperatorIsNotBlank: "é_is not blank_È",
    numberOperatorIs: "é_is_È", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "é_is not_È",
    numberOperatorIsAtLeast: "é_is at least_È",
    numberOperatorIsLessThan: "é_is less than_È",
    numberOperatorIsAtMost: "é_is at most_È",
    numberOperatorIsGreaterThan: "é_is greater than_È",
    numberOperatorIsBetween: "é_is between_È",
    numberOperatorIsNotBetween: "é_is not between_È",
    numberOperatorIsBlank: "é_is blank_È",
    numberOperatorIsNotBlank: "é_is not blank_È"
});