define({
    ok: "á_OK_Ó",
    cancel: "á_Cancel_Ó",
    exportMessage: "á_Export data to CSV file?_Ó",
    exportFiles: "á_Export to CSV_Ó",
    options: "á_Options_Ó",
    zoomto: "á_Zoom to_Ó",
    highlight: "á_Highlight Graphics_Ó",
    selectAll: "á_Select All Pages_Ó",
    selectPage: "á_Select Current Page_Ó",
    clearSelection: "á_Clear Selection_Ó",
    filterByExtent: "á_Filter by Map Extent_Ó",
    refresh: "á_Refresh_Ó",
    selected: "á_selected_Ó",
    transparent: "á_Transparent Mode_Ó",
    indicate: "á_Locate Selection_Ó",
    columns: "á_Show/Hide Columns_Ó",
    selectionSymbol: "á_Selection Symbol_Ó",
    closeMessage: "á_Hide table[Show it again in layer list]_Ó",
    dataNotAvailable: "á_Data not available!<br>Click [Refresh] button to have a try_Ó"
});