define({
  root: {
    executeQueryTip: "Click one of the following task items to execute query.",
    invalidConfig: "Invalid configuration. Please use Query setting page to get correct configuration.",
    queryParams: "Options",
    parameters: "OPTIONS",
    queries: "QUERIES",
    apply: "APPLY",
    queryResults: "Results",
    clear: "Clear",
    noResults: "No feature found.",
    queryError: "Query failed !",
    numberFound: "Number of features found",
    mapExtentTip:"Limit the results to the current map extent.",
    noValue:"No value",
    and:"and",
    friendlyDatePattern:"MM/dd/yyyy",
    stringOperatorIs: "is", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "is not",
    stringOperatorStartsWith: "starts with",
    stringOperatorEndsWith: "ends with",
    stringOperatorContains: "contains",
    stringOperatorDoesNotContain: "does not contain",
    stringOperatorIsBlank: "is blank",
    stringOperatorIsNotBlank: "is not blank",
    dateOperatorIsOn: "is on", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "is not on",
    dateOperatorIsBefore: "is before",
    dateOperatorIsAfter: "is after",
    dateOperatorDays: "days",
    dateOperatorWeeks: "weeks", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "months",
    dateOperatorInTheLast: "in the last",
    dateOperatorNotInTheLast: "not in the last",
    dateOperatorIsBetween: "is between",
    dateOperatorIsNotBetween: "is not between",
    dateOperatorIsBlank: "is blank",
    dateOperatorIsNotBlank: "is not blank",
    numberOperatorIs: "is", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "is not",
    numberOperatorIsAtLeast: "is at least",
    numberOperatorIsLessThan: "is less than",
    numberOperatorIsAtMost: "is at most",
    numberOperatorIsGreaterThan: "is greater than",
    numberOperatorIsBetween: "is between",
    numberOperatorIsNotBetween: "is not between",
    numberOperatorIsBlank: "is blank",
    numberOperatorIsNotBlank: "is not blank",
    operationalLayerTip:"Add result as operational layer",
    queryResult:"Query Result",
    specifyParamsTip:"Specify parameters for this task",
    useSpatialFilter:"Use spatial filter",
    useCurrentMapExtent:"Use current map extent",
    drawGraphicOnMap:"Draw a graphic on the map",
    specifySpatialFilterMsg:"Please specify spatial filter for this task.",
    clearResults: "CLEAR RESULTS",
    operationalTip:'With this option checked, results will be kept on the map until the "${clearResults}" button clicked.',
    noneQueryTip:"There is no pre-configured query tasks available. Please contact you application creator to add it.",
    noPermissionsMsg:"You do not have permissions to access this service."
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": true
});