/*
 COPYRIGHT 2009 ESRI

 TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL
 Unpublished material - all rights reserved under the
 Copyright Laws of the United States and applicable international
 laws, treaties, and conventions.

 For additional information, contact:
 Environmental Systems Research Institute, Inc.
 Attn: Contracts and Legal Services Department
 380 New York Street
 Redlands, California, 92373
 USA

 email: contracts@esri.com
 */
//>>built
define("esri/dijit/Legend","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/json dojo/has dojo/sniff dojo/DeferredList dojo/json dojo/dom dojo/dom-construct dojo/dom-style dijit/_Widget dojox/gfx dojox/html/entities esri/kernel esri/config esri/request esri/renderers/SimpleRenderer esri/renderers/UniqueValueRenderer esri/renderers/ClassBreaksRenderer esri/renderers/ScaleDependentRenderer esri/symbols/jsonUtils esri/dijit/_EventedWidget dojo/i18n!esri/nls/jsapi".split(" "),
function(x,q,k,h,y,s,L,z,A,n,d,p,B,C,D,E,u,v,F,G,H,I,w,J,K){var t=x([J,B],{declaredClass:"esri.dijit.Legend",widgetsInTemplate:!1,layers:null,alignRight:!1,hoverLabelShowing:!1,_ieTimer:100,constructor:function(a,b){q.mixin(this,K.widgets.legend);a=a||{};a.map?b?(this.map=a.map,this.layerInfos=a.layerInfos,this._respectCurrentMapScale=!1===a.respectCurrentMapScale?!1:!0,this.arrangement=a.arrangement===t.ALIGN_RIGHT?t.ALIGN_RIGHT:t.ALIGN_LEFT,this.arrangement===t.ALIGN_RIGHT&&(this.alignRight=!0),
this.autoUpdate=!1===a.autoUpdate?!1:!0,this._surfaceItems=[]):console.error("esri.dijit.Legend: must specify a container for the legend"):console.error("esri.dijit.Legend: unable to find the 'map' property in parameters")},startup:function(){this.inherited(arguments);this._initialize();s("ie")&&(this._repaintItems=q.hitch(this,this._repaintItems),setTimeout(this._repaintItems,this._ieTimer))},destroy:function(){this._deactivate();this._removeHoverHandlers();this.inherited(arguments)},refresh:function(a){if(this.domNode){a?
(this.layerInfos=a,this.layers=[],k.forEach(this.layerInfos,function(a){this._isSupportedLayerType(a.layer)&&(a.title&&(a.layer._titleForLegend=a.title),a.layer._hideDefaultSymbol=!1===a.defaultSymbol?!0:!1,a.hideLayers?(a.layer._hideLayersInLegend=a.hideLayers,this._addSubLayersToHide(a)):a.layer._hideLayersInLegend=[],a.hoverLabel&&(a.layer._hoverLabel=a.hoverLabel),a.hoverLabels&&(a.layer._hoverLabels=a.hoverLabels),this.layers.push(a.layer))},this)):this.useAllMapLayers&&(this.layers=this.layerInfos=
null);for(a=this.domNode.children.length-1;0<=a;a--)d.destroy(this.domNode.children[a]);this._removeHoverHandlers();this.startup()}},_legendUrl:"http://utility.arcgis.com/sharing/tools/legend",_initialize:function(){this.layerInfos&&(this.layers=[],k.forEach(this.layerInfos,function(a){this._isSupportedLayerType(a.layer)&&(a.title&&(a.layer._titleForLegend=a.title),a.layer._hideDefaultSymbol=!1===a.defaultSymbol?!0:!1,a.hideLayers?(a.layer._hideLayersInLegend=a.hideLayers,this._addSubLayersToHide(a)):
a.layer._hideLayersInLegend=[],a.hoverLabel&&(a.layer._hoverLabel=a.hoverLabel),a.hoverLabels&&(a.layer._hoverLabels=a.hoverLabels),this.layers.push(a.layer))},this));this.useAllMapLayers=!1;if(!this.layers){this.useAllMapLayers=!0;this.layers=[];var a=[],b=[];k.forEach(this.map.layerIds,function(c){c=this.map.getLayer(c);var e;this._isSupportedLayerType(c)&&(c.arcgisProps&&c.arcgisProps.title&&(c._titleForLegend=c.arcgisProps.title),this.layers.push(c));"esri.layers.KMLLayer"==c.declaredClass&&(e=
c.getLayers(),k.forEach(e,function(b){a.push(b.id)},this));"esri.layers.GeoRSSLayer"==c.declaredClass&&(e=c.getFeatureLayers(),k.forEach(e,function(a){b.push(a.id)},this))},this);k.forEach(this.map.graphicsLayerIds,function(c){var e=this.map.getLayer(c);-1==k.indexOf(a,c)&&-1==k.indexOf(b,c)&&(this._isSupportedLayerType(e)&&e._params&&e._params.drawMode)&&(e.arcgisProps&&e.arcgisProps.title&&(e._titleForLegend=e.arcgisProps.title),this.layers.push(e))},this)}this._createLegend()},_activate:function(){this._deactivate();
this.autoUpdate&&(this._respectCurrentMapScale&&(this._ozeConnect=h.connect(this.map,"onZoomEnd",this,"_refreshLayers")),this.useAllMapLayers&&(this._olaConnect=h.connect(this.map,"onLayerAdd",this,"_updateAllMapLayers"),this._olrConnect=h.connect(this.map,"onLayerRemove",this,"_updateAllMapLayers"),this._olroConnect=h.connect(this.map,"onLayersReordered",this,"_updateAllMapLayers")),k.forEach(this.layers,function(a){a.ovcConnect=h.connect(a,"onVisibilityChange",this,"_refreshLayers");a.oscConnect=
h.connect(a,"onScaleRangeChange",this,"_refreshLayers");"esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass&&a.supportsDynamicLayers&&(a.odcConnect=h.connect(a,"_onDynamicLayersChange",q.hitch(this,"_updateDynamicLayers",a)));"esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&(a.oirConnect=h.connect(a,"onRenderingChange",q.partial(this._updateImageServiceLayers,this,a)))},this))},_deactivate:function(){this._ozeConnect&&h.disconnect(this._ozeConnect);this._olaConnect&&h.disconnect(this._olaConnect);
this._olroConnect&&h.disconnect(this._olroConnect);this._olrConnect&&h.disconnect(this._olrConnect);k.forEach(this.layers,function(a){a.ovcConnect&&h.disconnect(a.ovcConnect);a.oscConnect&&h.disconnect(a.oscConnect);a.odcConnect&&h.disconnect(a.odcConnect);a.oirConnect&&h.disconnect(a.oirConnect)},this)},_updateDynamicLayers:function(a){delete a.legendResponse;this._refreshLayers()},_updateImageServiceLayers:function(a,b){delete b.legendResponse;a._refreshLayers()},_refreshLayers:function(){this.refresh()},
_updateAllMapLayers:function(){this.layers=[];k.forEach(this.map.layerIds,function(a){a=this.map.getLayer(a);this._isSupportedLayerType(a)&&this.layers.push(a)},this);k.forEach(this.map.graphicsLayerIds,function(a){a=this.map.getLayer(a);this._isSupportedLayerType(a)&&(a._params&&a._params.drawMode)&&this.layers.push(a)},this);this.refresh()},_createLegend:function(){var a=!1;p.set(this.domNode,"position","relative");d.create("div",{id:this.id+"_msg",innerHTML:this.NLS_creatingLegend+"..."},this.domNode);
var b=[];k.forEach(this.layers,function(c){if("esri.layers.KMLLayer"==c.declaredClass||"esri.layers.GeoRSSLayer"==c.declaredClass){var g;c.loaded?("esri.layers.KMLLayer"==c.declaredClass?g=c.getLayers():"esri.layers.GeoRSSLayer"==c.declaredClass&&(g=c.getFeatureLayers(),c._hideLayersInLegend&&(g=k.filter(g,function(a){return-1==k.indexOf(c._hideLayersInLegend,a.id)}))),k.forEach(g,function(a){"esri.layers.FeatureLayer"==a.declaredClass&&c._titleForLegend&&(a._titleForLegend=c._titleForLegend+" - ",
"esriGeometryPoint"==a.geometryType?a._titleForLegend+=this.NLS_points:"esriGeometryPolyline"==a.geometryType?a._titleForLegend+=this.NLS_lines:"esriGeometryPolygon"==a.geometryType&&(a._titleForLegend+=this.NLS_polygons),b.push(a))},this)):h.connect(c,"onLoad",q.hitch(this,function(){this.refresh(this.layerInfos)}))}else"esri.layers.WMSLayer"===c.declaredClass?c.loaded?c.visible&&(0<c.layerInfos.length&&k.some(c.layerInfos,function(a){return a.legendURL}))&&(d.create("div",{innerHTML:"\x3cspan class\x3d'esriLegendServiceLabel'\x3e"+
(c._titleForLegend||c.name||c.id)+"\x3c/span\x3e"},this.domNode),k.forEach(c.layerInfos,function(b){-1<k.indexOf(c.visibleLayers,b.name)&&(d.create("div",{innerHTML:"\x3cimg src\x3d'"+b.legendURL+"'/\x3e"},this.domNode),a=!0)},this)):h.connect(c,"onLoad",q.hitch(this,function(){this.refresh(this.layerInfos)})):b.push(c)},this);var c=[];k.forEach(b,function(a){if(a.loaded){if(!0===a.visible&&(a.layerInfos||a.renderer||"esri.layers.ArcGISImageServiceLayer"==a.declaredClass)){var b=d.create("div",{id:this.id+
"_"+a.id,style:"display: none;","class":"esriLegendService"});d.create("span",{innerHTML:this._getServiceTitle(a),"class":"esriLegendServiceLabel"},d.create("td",{align:this.alignRight?"right":"left"},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%"},b)))));d.place(b,this.id,"first");s("ie")&&p.set(n.byId(this.id+"_"+a.id),"display","none");a.legendResponse||a.renderer?this._createLegendForLayer(a):c.push(this._legendRequest(a))}}else var f=h.connect(a,"onLoad",this,function(a){h.disconnect(f);
f=null;this.refresh()})},this);0===c.length&&!a?(n.byId(this.id+"_msg").innerHTML=this.NLS_noLegend,this._activate()):(new z(c)).addCallback(q.hitch(this,function(b){a?n.byId(this.id+"_msg").innerHTML="":n.byId(this.id+"_msg").innerHTML=this.NLS_noLegend;this._activate()}))},_createLegendForLayer:function(a){if(a.legendResponse||a.renderer){var b=!1;if(a.legendResponse){var c=a.dynamicLayerInfos||a.layerInfos;c?k.forEach(c,function(c,g){if(!a._hideLayersInLegend||-1==k.indexOf(a._hideLayersInLegend,
c.id)){var f=this._buildLegendItems(a,c,g);b=b||f}},this):"esri.layers.ArcGISImageServiceLayer"==a.declaredClass&&(b=this._buildLegendItems(a,{id:0,name:null,title:a.name,subLayerIds:null,parentLayerId:-1},0))}else a.renderer&&(c=a.url?a.url.substring(a.url.lastIndexOf("/")+1,a.url.length):"fc_"+a.id,b=this._buildLegendItems(a,{id:c,name:null,subLayerIds:null,parentLayerId:-1},0));b&&(p.set(n.byId(this.id+"_"+a.id),"display","block"),p.set(n.byId(this.id+"_msg"),"display","none"))}},_legendRequest:function(a){if(a.loaded)return 10.01<=
a.version?this._legendRequestServer(a):this._legendRequestTools(a);h.connect(a,"onLoad",q.hitch(this,"_legendRequest"))},_legendRequestServer:function(a){var b=a.url,c=b.indexOf("?"),b=-1<c?b.substring(0,c)+"/legend"+b.substring(c):b+"/legend";(c=a._getToken())&&(b+="?token\x3d"+c);var e=q.hitch(this,"_processLegendResponse"),c={f:"json"};a._params.dynamicLayers&&(c.dynamicLayers=A.stringify(this._createDynamicLayers(a)),"[{}]"===c.dynamicLayers&&(c.dynamicLayers="[]"));a._params.bandIds&&(c.bandIds=
a._params.bandIds);a._params.renderingRule&&(c.renderingRule=a._params.renderingRule);return v({url:b,content:c,callbackParamName:"callback",load:function(b,c){e(a,b,c)},error:u.defaults.io.errorHandler})},_legendRequestTools:function(a){var b=a.url.toLowerCase().indexOf("/rest/"),b=a.url.substring(0,b)+a.url.substring(b+5,a.url.length),b=this._legendUrl+"?soapUrl\x3d"+window.escape(b);if(!s("ie")||8<s("ie"))b+="\x26returnbytes\x3dtrue";var c=q.hitch(this,"_processLegendResponse");return v({url:b,
content:{f:"json"},callbackParamName:"callback",load:function(b,g){c(a,b,g)},error:u.defaults.io.errorHandler})},_processLegendResponse:function(a,b){b&&b.layers?(a.legendResponse=b,n.byId(this.id+"_"+a.id)&&d.empty(n.byId(this.id+"_"+a.id)),d.create("span",{innerHTML:this._getServiceTitle(a),"class":"esriLegendServiceLabel"},d.create("td",{align:this.alignRight?"right":"left"},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%"},n.byId(this.id+"_"+a.id)))))),this._createLegendForLayer(a)):
console.log("Legend could not get generated for "+a.url+": "+y.toJson(b))},_buildLegendItems:function(a,b,c){var e=!1,g=n.byId(this.id+"_"+a.id),f=b.parentLayerId;if(b.subLayerIds)c=d.create("div",{id:this.id+"_"+a.id+"_"+b.id+"_group",style:"display: none;","class":-1==f?0<c?"esriLegendGroupLayer":"":this.alignRight?"esriLegendRight":"esriLegendLeft"},-1==f?g:n.byId(this.id+"_"+a.id+"_"+f+"_group")),s("ie")&&p.set(n.byId(this.id+"_"+a.id+"_"+b.id+"_group"),"display","none"),d.create("td",{innerHTML:b.name.replace(/[\<]/g,
"\x26lt;").replace(/[\>]/g,"\x26gt;"),align:this.alignRight?"right":"left"},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%","class":"esriLegendLayerLabel"},c))));else{if(a.visibleLayers&&-1==(","+a.visibleLayers+",").indexOf(","+b.id+","))return e;c=d.create("div",{id:this.id+"_"+a.id+"_"+b.id,style:"display:none;","class":-1<f?this.alignRight?"esriLegendRight":"esriLegendLeft":""},-1==f?g:n.byId(this.id+"_"+a.id+"_"+f+"_group"));s("ie")&&p.set(n.byId(this.id+"_"+a.id+"_"+b.id),
"display","none");d.create("td",{innerHTML:b.name?b.name.replace(/[\<]/g,"\x26lt;").replace(/[\>]/g,"\x26gt;"):"",align:this.alignRight?"right":"left"},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%","class":"esriLegendLayerLabel"},c))));a.legendResponse?e=e||this._buildLegendItems_Tools(a,b,c):a.renderer&&(e=e||this._buildLegendItems_Renderer(a,b,c))}return e},_buildLegendItems_Tools:function(a,b,c){var e=b.parentLayerId,g=this.map.getScale(),f=!1,r=function(a,b){var c,e;for(c=
0;c<a.length;c++)if(b.dynamicLayerInfos)for(e=0;e<b.dynamicLayerInfos[e].length;e++){if(b.dynamicLayerInfos[e].mapLayerId==a[c].layerId)return a[c]}else if(b.id==a[c].layerId)return a[c];return{}};if(!this._respectCurrentMapScale||this._respectCurrentMapScale&&this._isLayerInScale(a,b,g)){var l=r(a.legendResponse.layers,b).legend;if(l){c=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c);var m=d.create("tbody",{},c);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(c,
a,b);k.forEach(l,function(c){if(!(10.1<=a.version&&!c.values&&1<l.length&&(a._hideDefaultSymbol||"\x3call other values\x3e"===c.label||!c.label)))if(c.url&&0===c.url.indexOf("http")||c.imageData&&0<c.imageData.length)f=!0,this._buildRow_Tools(c,m,a,b.id)},this)}}f&&(p.set(n.byId(this.id+"_"+a.id+"_"+b.id),"display","block"),-1<e&&(p.set(n.byId(this.id+"_"+a.id+"_"+e+"_group"),"display","block"),this._findParentGroup(a.id,a,e)));return f},_buildRow_Tools:function(a,b,c,e){var g=d.create("tr",{},b),
f;this.alignRight?(b=d.create("td",{align:"right"},g),f=d.create("td",{align:"right",width:35},g)):(f=d.create("td",{width:35},g),b=d.create("td",{},g));g=a.url;(!s("ie")||8<s("ie"))&&a.imageData&&0<a.imageData.length?g="data:image/png;base64,"+a.imageData:0!==a.url.indexOf("http")&&(g=c.url+"/"+e+"/images/"+a.url,(e=c._getToken())&&(g+="?token\x3d"+e));e=d.create("img",{src:g,border:0,style:"opacity:"+c.opacity},f);d.create("td",{innerHTML:a.label.replace(/[\&]/g,"\x26amp;").replace(/[\<]/g,"\x26lt;").replace(/[\>]/g,
"\x26gt;").replace(/^#/,""),align:this.alignRight?"right":"left"},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%",dir:"ltr"},b))));9>s("ie")&&(e.style.filter="alpha(opacity\x3d"+100*c.opacity+")")},_buildLegendItems_Renderer:function(a,b,c){var e=b.parentLayerId,g=this.map,f=g.getScale(),r=!1;if(!this._respectCurrentMapScale||this._isLayerInScale(a,b,f)){var l,m=a.renderer;if(m instanceof I&&(m=(m="zoom"===m.rangeType?m.getRendererInfoByZoom(g.getZoom()):m.getRendererInfoByScale(f))&&
m.renderer,!m))return!1;m instanceof G?m.infos&&0<m.infos.length&&(r=!0,c=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),l=d.create("tbody",{},c),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(c,a,b),k.forEach(m.infos,function(b,c){var e=null;a._editable&&a.types&&(e=this._getTemplateFromTypes(a.types,b.value));var f=b.label;if(!f||0===f.length)f=b.value;this._buildRow_Renderer(a,b.symbol,f,e,l)},this)):m instanceof H?m.infos&&0<m.infos.length&&(r=
!0,c=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),l=d.create("tbody",{},c),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(c,a,b),k.forEach(m.infos,function(b,c){var e=b.label;if(!e||0===e.length)e=b.minValue+" - "+b.maxValue;this._buildRow_Renderer(a,b.symbol,e,null,l)},this)):m instanceof F&&(r=!0,c=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),l=d.create("tbody",{},c),(a._hoverLabel||a._hoverLabels)&&
this._createHoverAction(c,a,b),c=null,a._editable&&(a.templates&&0<a.templates.length)&&(c=a.templates[0]),this._buildRow_Renderer(a,m.symbol,m.label,c,l));!a._hideDefaultSymbol&&m.defaultSymbol&&(r=!0,this._buildRow_Renderer(a,m.defaultSymbol,m.defaultLabel?m.defaultLabel:"others",null,l))}r&&(p.set(n.byId(this.id+"_"+a.id+"_"+b.id),"display","block"),-1<e&&(p.set(n.byId(this.id+"_"+a.id+"_"+e+"_group"),"display","block"),this._findParentGroup(a.id,e)));return r},_buildRow_Renderer:function(a,b,
c,e,g){var f=d.create("tr",{},g),r;this.alignRight?(g=d.create("td",{align:"right"},f),r=d.create("td",{align:"right",width:35},f)):(r=d.create("td",{width:35},f),g=d.create("td",{},f));var l=f=30;"simplemarkersymbol"==b.type?(f=Math.min(Math.max(f,b.size+12),125),l=Math.min(Math.max(l,b.size+12),125)):"picturemarkersymbol"==b.type&&(f=Math.min(Math.max(f,b.width),125),l=Math.min(b.height?b.height:l,125));r=d.create("div",{style:"width:"+f+"px;height:"+l+"px;"},r);d.create("td",{innerHTML:c?c.replace(/[\&]/g,
"\x26amp;").replace(/[\<]/g,"\x26lt;").replace(/[\>]/g,"\x26gt;").replace(/^#/,""):"",align:this.alignRight?"right":"left"},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%"},g))));a=this._drawSymbol(r,b,f,l,e,a.opacity);this._surfaceItems.push(a)},_drawSymbol:function(a,b,c,e,g,f){b=w.fromJson(b.toJson());var d;if("simplelinesymbol"===b.type||"cartographiclinesymbol"===b.type||"textsymbol"===b.type){if(!b.color)return;d=b.color.toRgba();d[3]*=f;b.color.setColor(d)}else if("simplemarkersymbol"===
b.type||"simplefillsymbol"===b.type){if(!b.color)return;d=b.color.toRgba();d[3]*=f;b.color.setColor(d);b.outline&&b.outline.color&&(d=b.outline.color.toRgba(),d[3]*=f,b.outline.color.setColor(d))}else"picturemarkersymbol"===b.type&&(a.style.opacity=f,a.style.filter="alpha(opacity\x3d("+100*f+"))");a=C.createSurface(a,c,e);s("ie")&&(f=a.getEventSource(),p.set(f,"position","relative"),p.set(f.parentNode,"position","relative"));g=this._getDrawingToolShape(b,g)||w.getShapeDescriptors(b);var l;try{l=a.createShape(g.defaultShape).setFill(g.fill).setStroke(g.stroke)}catch(k){a.clear();
a.destroy();return}d=l.getBoundingBox();g=d.width;b=d.height;f=-(d.x+g/2);d=-(d.y+b/2);var h=a.getDimensions();f={dx:f+h.width/2,dy:d+h.height/2};if(g>c||b>e)c=((c<e?c:e)-5)/(g>b?g:b),q.mixin(f,{xx:c,yy:c});l.applyTransform(f);return a},_getDrawingToolShape:function(a,b){var c;switch(b?b.drawingTool||null:null){case "esriFeatureEditToolArrow":c={type:"path",path:"M 10,1 L 3,8 L 3,5 L -15,5 L -15,-2 L 3,-2 L 3,-5 L 10,1 E"};break;case "esriFeatureEditToolTriangle":c={type:"path",path:"M -10,14 L 2,-10 L 14,14 L -10,14 E"};
break;case "esriFeatureEditToolRectangle":c={type:"path",path:"M -10,-10 L 10,-10 L 10,10 L -10,10 L -10,-10 E"};break;case "esriFeatureEditToolCircle":c={type:"circle",cx:0,cy:0,r:10};break;case "esriFeatureEditToolEllipse":c={type:"ellipse",cx:0,cy:0,rx:10,ry:5};break;default:return null}return{defaultShape:c,fill:a.getFill(),stroke:a.getStroke()}},_repaintItems:function(){k.forEach(this._surfaceItems,function(a){this._repaint(a)},this)},_repaint:function(a){if(a){a.getStroke&&a.setStroke&&a.setStroke(a.getStroke());
try{a.getFill&&a.setFill&&a.setFill(a.getFill())}catch(b){}a.children&&q.isArray(a.children)&&k.forEach(a.children,this._repaint,this)}},_createHoverAction:function(a,b,c){var e=b._hoverLabel||b._hoverLabels[c.id];e&&(b.mouseMoveHandler=b.mouseMoveHandler||{},b.mouseMoveHandler[c.id]=h.connect(a,"onmousemove",q.hitch(this,function(a,b){this.mouseX=b.clientX;this.mouseY=b.clientY;this.hoverLabelShowing&&(this.hoverLabelShowing=!1,p.set(n.byId(this.id+"_hoverLabel"),"display","none"));setTimeout(q.hitch(this,
function(a,b,c){if(a==this.mouseX&&b==this.mouseY&&!this.hoverLabelShowing)if(this.hoverLabelShowing=!0,n.byId(this.id+"_hoverLabel")){var e=n.byId(this.id+"_hoverLabel");e.innerHTML="\x3cspan\x3e"+c+"\x3c/span\x3e";p.set(e,"top",b+"px");p.set(e,"left",a+15+"px");p.set(e,"display","")}else d.create("div",{innerHTML:"\x3cspan\x3e"+c+"\x3c/span\x3e",id:this.id+"_hoverLabel","class":"esriLegendHoverLabel",style:{top:b+"px",left:a+15+"px"}},document.body)},b.clientX,b.clientY,a),500)},e)),b.mouseOutHandler=
b.mouseOutHandler||{},b.mouseOutHandler[c.id]=h.connect(a,"onmouseout",q.hitch(this,function(a){this.mouseY=this.mouseX=-1;this.hoverLabelShowing&&(this.hoverLabelShowing=!1,p.set(n.byId(this.id+"_hoverLabel"),"display","none"))})))},_removeHoverHandlers:function(){var a;k.forEach(this.layers,function(b){if(b.mouseMoveHandler)for(a in b.mouseMoveHandler)h.disconnect(b.mouseMoveHandler[a]);if(b.mouseOutHandler)for(a in b.mouseOutHandler)h.disconnect(b.mouseOutHandler[a])})},_createDynamicLayers:function(a){var b=
[],c;k.forEach(a.dynamicLayerInfos||a.layerInfos,function(e){c={id:e.id};c.source=e.source&&e.source.toJson();var d;a.layerDefinitions&&a.layerDefinitions[e.id]&&(d=a.layerDefinitions[e.id]);d&&(c.definitionExpression=d);var f;a.layerDrawingOptions&&a.layerDrawingOptions[e.id]&&(f=a.layerDrawingOptions[e.id]);f&&(c.drawingInfo=f.toJson());c.minScale=e.minScale||0;c.maxScale=e.maxScale||0;b.push(c)});return b},_getTemplateFromTypes:function(a,b){var c;for(c=0;c<a.length;c++)if(a[c].id==b&&a[c].templates&&
0<a[c].templates.length)return a[c].templates[0];return null},_findParentGroup:function(a,b,c){var e,d=b.dynamicLayerInfos||b.layerInfos;for(e=0;e<d.length;e++)if(c==d[e].id){-1<d[e].parentLayerId&&(p.set(n.byId(this.id+"_"+a+"_"+d[e].parentLayerId+"_group"),"display","block"),this._findParentGroup(a,b,d[e].parentLayerId));break}},_addSubLayersToHide:function(a){function b(c,e){var d=a.layer.dynamicLayerInfos||a.layer.layerInfos,f,h;for(f=0;f<d.length;f++)if(d[f].id===c&&d[f].subLayerIds)for(h=0;h<
d[f].subLayerIds.length;h++){var l=d[f].subLayerIds[h];-1===k.indexOf(e,l)&&(e.push(l),b(l,e))}}a.layer.layerInfos&&k.forEach(a.layer._hideLayersInLegend,function(c){b(c,a.layer._hideLayersInLegend)})},_isLayerInScale:function(a,b,c){var d,g=!0;if(a.legendResponse&&a.legendResponse.layers)for(d=0;d<a.legendResponse.layers.length;d++){var f=a.legendResponse.layers[d];if(b.id==f.layerId){var h,k;!a.minScale&&0!==a.minScale||!a.maxScale&&0!==a.maxScale?(0==f.minScale&&a.tileInfo&&(h=a.tileInfo.lods[0].scale),
0==f.maxScale&&a.tileInfo&&(k=a.tileInfo.lods[a.tileInfo.lods.length-1].scale)):(h=Math.min(a.minScale,f.minScale)||a.minScale||f.minScale,k=Math.max(a.maxScale,f.maxScale));if(0<h&&h<c||k>c)g=!1;break}}else if(a.minScale||a.maxScale)if(a.minScale&&a.minScale<c||a.maxScale&&a.maxScale>c)g=!1;return g},_getServiceTitle:function(a){var b=a._titleForLegend;b||((b=a.url)?-1<a.url.indexOf("/MapServer")?(b=a.url.substring(0,a.url.indexOf("/MapServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):-1<a.url.indexOf("/ImageServer")?
(b=a.url.substring(0,a.url.indexOf("/ImageServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):-1<a.url.indexOf("/FeatureServer")&&(b=a.url.substring(0,a.url.indexOf("/FeatureServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):b="",a.name&&(b=0<b.length?b+(" - "+a.name):a.name));return D.encode(b)},_isSupportedLayerType:function(a){return a&&("esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass||"esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&10.2<=a.version||"esri.layers.ArcGISTiledMapServiceLayer"===
a.declaredClass||"esri.layers.FeatureLayer"===a.declaredClass||"esri.layers.KMLLayer"===a.declaredClass||"esri.layers.GeoRSSLayer"===a.declaredClass||"esri.layers.WMSLayer"===a.declaredClass)?!0:!1}});q.mixin(t,{ALIGN_LEFT:0,ALIGN_RIGHT:1});s("extend-esri")&&q.setObject("dijit.Legend",t,E);return t});