define({
    ok: "é_OK_È",
    cancel: "é_Cancel_È",
    exportMessage: "é_Export data to CSV file?_È",
    exportFiles: "é_Export to CSV_È",
    options: "é_Options_È",
    zoomto: "é_Zoom to_È",
    highlight: "é_Highlight Graphics_È",
    selectAll: "é_Select All Pages_È",
    selectPage: "é_Select Current Page_È",
    clearSelection: "é_Clear Selection_È",
    filterByExtent: "é_Filter by Map Extent_È",
    refresh: "é_Refresh_È",
    selected: "é_selected_È",
    transparent: "é_Transparent Mode_È",
    indicate: "é_Locate Selection_È",
    columns: "é_Show/Hide Columns_È",
    selectionSymbol: "é_Selection Symbol_È",
    closeMessage: "é_Hide table[Show it again in layer list]_È",
    dataNotAvailable: "é_Data not available!<br>Click [Refresh] button to have a try_È"
});