define({
		queries:"ä_Queries_Ü",
		addNew: "ä_Add New_Ü",
		setSource: "ä_Set Source_Ü",
		setQuerySource: "ä_Set query source_Ü",
		name: "ä_Name_Ü",
		querySource: "ä_Query Source_Ü",
		queryName:"ä_Query Name_Ü",
		queryDefinition:"ä_Query Definition_Ü",
		resultsSetting:"ä_Results Setting_Ü",
		resultSettingTip:"ä_Define below for showing information about features that are resulted from the query operation._Ü",
		resultItemTitle:"ä_Result Item Title_Ü",
		resultItemContent:"ä_Result Item Content_Ü",
		fieldsSetTip:"ä_Check the fields you want to display. Select a field to change its alias,order it and format it._Ü",
		addField:"ä_Add Field_Ü",
		visibility:"ä_Visibility_Ü",
		alias:"ä_Alias_Ü",
		specialType:"ä_Special Type_Ü",
		actions:"ä_Actions_Ü",
		none:"ä_None_Ü",
		link:"ä_Link_Ü",
		image:"ä_Image_Ü",
		noField:"ä_No field_Ü",
		operationalLayerTip:"ä_Add result as operational layer_Ü",
		setLayerSymbolTip:"ä_Set the symbol of query result._Ü",
		setSelectedSymbolTip:"ä_Set the symbol of selected feature._Ü",
		notUseFilter:"ä_Don't use filter_Ü",
		setSourceTip:"ä_Please set query source !_Ü",
		setFilterTip:"ä_Please set filter correctly !_Ü",
		ok:"ä_Ok_Ü",
		cancel:"ä_Cancel_Ü"
});