define({
    taskUrl: "Š_Task URL_ä",
    serviceURLPlaceholder: "Š_Please input Geoprocessing task URL_ä",
    ok: "Š_OK_ä",
    cancel: "Š_Cancel_ä",
    layer: "Š_Layer_ä",
    action: "Š_Action_ä",
    input: "Š_Input_ä",
    output: "Š_Output_ä",
    name: "Š_Name_ä",
    type: "Š_Type_ä",
    required: "Š_Required_ä",
    layerOrder: "Š_Layer order_ä",
    options: "Š_Options_ä",
    defaultValue: "Š_Default Value_ä",
    inputFeatureBy: "Š_Input Feature by_ä",
    renderer: "Š_Renderer_ä",
    displayType: "Š_Display type_ä",
    label: "Š_Label_ä",
    tooltip: "Š_Tooltip_ä",
    visible: "Š_Visible_ä",
    helpUrl: "Š_Help URL_ä",
    useResultMapService: "Š_Use the drawing options of result map service_ä",
    drawOnMap: "Š_Interactively drawing on the map_ä",
    selectLayer: "Š_Selecting a layer from the map_ä",
    url: "Š_URL_ä",
    symbol: "Š_Symbol_ä",
    shareResults: "Š_Add result as operational layer_ä"
});