define({
    executeQueryTip: "Å_Click one of the following items to execute query._ö",
    invalidConfig: "Å_Invalid config. Please use Query setting page to get correct config._ö",
    queryParams: "Å_Query Parameters_ö",
    parameters: "Å_Parameters_ö",
    queries: "Å_Queries_ö",
    apply: "Å_Apply_ö",
    queryResults: "Å_Query Results_ö",
    clear: "Å_Clear_ö",
    noResults: "Å_No results_ö",
    queryError: "Å_Query failed !_ö",
    numberFound: "Å_Number of features found_ö",
    mapExtentTip:"Å_Limit the results to the current map extent._ö",
    noValue:"Å_No value_ö",
    and:"Å_and_ö",
    friendlyDatePattern:"Å_MM/dd/yyyy_ö",
    stringOperatorIs: "Å_is_ö", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "Å_is not_ö",
    stringOperatorStartsWith: "Å_starts with_ö",
    stringOperatorEndsWith: "Å_ends with_ö",
    stringOperatorContains: "Å_contains_ö",
    stringOperatorDoesNotContain: "Å_does not contain_ö",
    stringOperatorIsBlank: "Å_is blank_ö",
    stringOperatorIsNotBlank: "Å_is not blank_ö",
    dateOperatorIsOn: "Å_is on_ö", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "Å_is not on_ö",
    dateOperatorIsBefore: "Å_is before_ö",
    dateOperatorIsAfter: "Å_is after_ö",
    dateOperatorDays: "Å_days_ö",
    dateOperatorWeeks: "Å_weeks_ö", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "Å_months_ö",
    dateOperatorInTheLast: "Å_in the last_ö",
    dateOperatorNotInTheLast: "Å_not in the last_ö",
    dateOperatorIsBetween: "Å_is between_ö",
    dateOperatorIsNotBetween: "Å_is not between_ö",
    dateOperatorIsBlank: "Å_is blank_ö",
    dateOperatorIsNotBlank: "Å_is not blank_ö",
    numberOperatorIs: "Å_is_ö", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "Å_is not_ö",
    numberOperatorIsAtLeast: "Å_is at least_ö",
    numberOperatorIsLessThan: "Å_is less than_ö",
    numberOperatorIsAtMost: "Å_is at most_ö",
    numberOperatorIsGreaterThan: "Å_is greater than_ö",
    numberOperatorIsBetween: "Å_is between_ö",
    numberOperatorIsNotBetween: "Å_is not between_ö",
    numberOperatorIsBlank: "Å_is blank_ö",
    numberOperatorIsNotBlank: "Å_is not blank_ö"
});