define({
    executeQueryTip: "ø_Click one of the following items to execute query._å",
    invalidConfig: "ø_Invalid config. Please use Query setting page to get correct config._å",
    queryParams: "ø_Query Parameters_å",
    parameters: "ø_Parameters_å",
    queries: "ø_Queries_å",
    apply: "ø_Apply_å",
    queryResults: "ø_Query Results_å",
    clear: "ø_Clear_å",
    noResults: "ø_No results_å",
    queryError: "ø_Query failed !_å",
    numberFound: "ø_Number of features found_å",
    mapExtentTip:"ø_Limit the results to the current map extent._å",
    noValue:"ø_No value_å",
    and:"ø_and_å",
    friendlyDatePattern:"ø_MM/dd/yyyy_å",
    stringOperatorIs: "ø_is_å", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "ø_is not_å",
    stringOperatorStartsWith: "ø_starts with_å",
    stringOperatorEndsWith: "ø_ends with_å",
    stringOperatorContains: "ø_contains_å",
    stringOperatorDoesNotContain: "ø_does not contain_å",
    stringOperatorIsBlank: "ø_is blank_å",
    stringOperatorIsNotBlank: "ø_is not blank_å",
    dateOperatorIsOn: "ø_is on_å", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "ø_is not on_å",
    dateOperatorIsBefore: "ø_is before_å",
    dateOperatorIsAfter: "ø_is after_å",
    dateOperatorDays: "ø_days_å",
    dateOperatorWeeks: "ø_weeks_å", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "ø_months_å",
    dateOperatorInTheLast: "ø_in the last_å",
    dateOperatorNotInTheLast: "ø_not in the last_å",
    dateOperatorIsBetween: "ø_is between_å",
    dateOperatorIsNotBetween: "ø_is not between_å",
    dateOperatorIsBlank: "ø_is blank_å",
    dateOperatorIsNotBlank: "ø_is not blank_å",
    numberOperatorIs: "ø_is_å", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "ø_is not_å",
    numberOperatorIsAtLeast: "ø_is at least_å",
    numberOperatorIsLessThan: "ø_is less than_å",
    numberOperatorIsAtMost: "ø_is at most_å",
    numberOperatorIsGreaterThan: "ø_is greater than_å",
    numberOperatorIsBetween: "ø_is between_å",
    numberOperatorIsNotBetween: "ø_is not between_å",
    numberOperatorIsBlank: "ø_is blank_å",
    numberOperatorIsNotBlank: "ø_is not blank_å"
});