define({
		queries:"é_Queries_È",
		addNew: "é_Add New_È",
		setSource: "é_Set Source_È",
		setQuerySource: "é_Set query source_È",
		name: "é_Name_È",
		querySource: "é_Query Source_È",
		queryName:"é_Query Name_È",
		queryDefinition:"é_Query Definition_È",
		resultsSetting:"é_Results Setting_È",
		resultSettingTip:"é_Define below for showing information about features that are resulted from the query operation._È",
		resultItemTitle:"é_Result Item Title_È",
		resultItemContent:"é_Result Item Content_È",
		fieldsSetTip:"é_Check the fields you want to display. Select a field to change its alias,order it and format it._È",
		addField:"é_Add Field_È",
		visibility:"é_Visibility_È",
		alias:"é_Alias_È",
		specialType:"é_Special Type_È",
		actions:"é_Actions_È",
		none:"é_None_È",
		link:"é_Link_È",
		image:"é_Image_È",
		noField:"é_No field_È",
		operationalLayerTip:"é_Add result as operational layer_È",
		setLayerSymbolTip:"é_Set the symbol of query result._È",
		setSelectedSymbolTip:"é_Set the symbol of selected feature._È",
		notUseFilter:"é_Don't use filter_È",
		setSourceTip:"é_Please set query source !_È",
		setFilterTip:"é_Please set filter correctly !_È",
		ok:"é_Ok_È",
		cancel:"é_Cancel_È"
});