define({
		queries:"Į_Queries_š",
		addNew: "Į_Add New_š",
		setSource: "Į_Set Source_š",
		setQuerySource: "Į_Set query source_š",
		name: "Į_Name_š",
		querySource: "Į_Query Source_š",
		queryName:"Į_Query Name_š",
		queryDefinition:"Į_Query Definition_š",
		resultsSetting:"Į_Results Setting_š",
		resultSettingTip:"Į_Define below for showing information about features that are resulted from the query operation._š",
		resultItemTitle:"Į_Result Item Title_š",
		resultItemContent:"Į_Result Item Content_š",
		fieldsSetTip:"Į_Check the fields you want to display. Select a field to change its alias,order it and format it._š",
		addField:"Į_Add Field_š",
		visibility:"Į_Visibility_š",
		alias:"Į_Alias_š",
		specialType:"Į_Special Type_š",
		actions:"Į_Actions_š",
		none:"Į_None_š",
		link:"Į_Link_š",
		image:"Į_Image_š",
		noField:"Į_No field_š",
		operationalLayerTip:"Į_Add result as operational layer_š",
		setLayerSymbolTip:"Į_Set the symbol of query result._š",
		setSelectedSymbolTip:"Į_Set the symbol of selected feature._š",
		notUseFilter:"Į_Don't use filter_š",
		setSourceTip:"Į_Please set query source !_š",
		setFilterTip:"Į_Please set filter correctly !_š",
		ok:"Į_Ok_š",
		cancel:"Į_Cancel_š"
});