define({
  root: {
    add: "Click to Add a New Bookmark",
    title: "Title",
    placeholderBookmarkName: "Bookmark Name",
    ok: "OK",
    cancel: "Cancel",
    warning: "Please finish the edit!",
    edit: "Edit bookmark",
    errorNameExist: "Bookmark exists!",
    errorNameNull: "Invalid bookmark name!",
    addBookmark: "Create a New Bookmark",
    thumbnail: "Thumbnail",
    thumbnailHint: "Click image to update"
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": true
});