define({
    taskUrl: "Å_Task URL_ö",
    serviceURLPlaceholder: "Å_Please input Geoprocessing task URL_ö",
    ok: "Å_OK_ö",
    cancel: "Å_Cancel_ö",
    layer: "Å_Layer_ö",
    action: "Å_Action_ö",
    input: "Å_Input_ö",
    output: "Å_Output_ö",
    name: "Å_Name_ö",
    type: "Å_Type_ö",
    required: "Å_Required_ö",
    layerOrder: "Å_Layer order_ö",
    options: "Å_Options_ö",
    defaultValue: "Å_Default Value_ö",
    inputFeatureBy: "Å_Input Feature by_ö",
    renderer: "Å_Renderer_ö",
    displayType: "Å_Display type_ö",
    label: "Å_Label_ö",
    tooltip: "Å_Tooltip_ö",
    visible: "Å_Visible_ö",
    helpUrl: "Å_Help URL_ö",
    useResultMapService: "Å_Use the drawing options of result map service_ö",
    drawOnMap: "Å_Interactively drawing on the map_ö",
    selectLayer: "Å_Selecting a layer from the map_ö",
    url: "Å_URL_ö",
    symbol: "Å_Symbol_ö",
    shareResults: "Å_Add result as operational layer_ö"
});