define({
		queries:"Ĳ_Queries_ä",
		addNew: "Ĳ_Add New_ä",
		setSource: "Ĳ_Set Source_ä",
		setQuerySource: "Ĳ_Set query source_ä",
		name: "Ĳ_Name_ä",
		querySource: "Ĳ_Query Source_ä",
		queryName:"Ĳ_Query Name_ä",
		queryDefinition:"Ĳ_Query Definition_ä",
		resultsSetting:"Ĳ_Results Setting_ä",
		resultSettingTip:"Ĳ_Define below for showing information about features that are resulted from the query operation._ä",
		resultItemTitle:"Ĳ_Result Item Title_ä",
		resultItemContent:"Ĳ_Result Item Content_ä",
		fieldsSetTip:"Ĳ_Check the fields you want to display. Select a field to change its alias,order it and format it._ä",
		addField:"Ĳ_Add Field_ä",
		visibility:"Ĳ_Visibility_ä",
		alias:"Ĳ_Alias_ä",
		specialType:"Ĳ_Special Type_ä",
		actions:"Ĳ_Actions_ä",
		none:"Ĳ_None_ä",
		link:"Ĳ_Link_ä",
		image:"Ĳ_Image_ä",
		noField:"Ĳ_No field_ä",
		operationalLayerTip:"Ĳ_Add result as operational layer_ä",
		setLayerSymbolTip:"Ĳ_Set the symbol of query result._ä",
		setSelectedSymbolTip:"Ĳ_Set the symbol of selected feature._ä",
		notUseFilter:"Ĳ_Don't use filter_ä",
		setSourceTip:"Ĳ_Please set query source !_ä",
		setFilterTip:"Ĳ_Please set filter correctly !_ä",
		ok:"Ĳ_Ok_ä",
		cancel:"Ĳ_Cancel_ä"
});