define({
    showArcgisBasemaps: "ı_Show ArcGIS Basemaps_İ",
    add: "ı_Click to add a new basemap_İ",
    edit: "ı_Properties_İ",
    title: "ı_Title_İ",
    thumbnail: "ı_Thumbnail_İ",
    thumbnailHint: "ı_Click image to update_İ",
    url: "ı_URL_İ",
    addlayer: "ı_Add layer_İ",
    actions: "ı_Actions_İ",
    warning: "ı_Incorrect input_İ",
    save: "ı_Back and Save_İ",
    back: "ı_Back and Cancel_İ",
    addUrl: "ı_Add URL_İ",
    autoCheck: "ı_Auto Check_İ",
    checking: "ı_Checking..._İ",
    ok: "ı_OK_İ",
    cancel: "ı_Cancel_İ",
    result: "ı_Save successfully_İ",
    spError: "ı_All basemaps added to the gallery need to have the same spatial reference._İ"
});