define({
    executeQueryTip: "å_Click one of the following items to execute query._ø",
    invalidConfig: "å_Invalid config. Please use Query setting page to get correct config._ø",
    queryParams: "å_Query Parameters_ø",
    parameters: "å_Parameters_ø",
    queries: "å_Queries_ø",
    apply: "å_Apply_ø",
    queryResults: "å_Query Results_ø",
    clear: "å_Clear_ø",
    noResults: "å_No results_ø",
    queryError: "å_Query failed !_ø",
    numberFound: "å_Number of features found_ø",
    mapExtentTip:"å_Limit the results to the current map extent._ø",
    noValue:"å_No value_ø",
    and:"å_and_ø",
    friendlyDatePattern:"å_MM/dd/yyyy_ø",
    stringOperatorIs: "å_is_ø", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "å_is not_ø",
    stringOperatorStartsWith: "å_starts with_ø",
    stringOperatorEndsWith: "å_ends with_ø",
    stringOperatorContains: "å_contains_ø",
    stringOperatorDoesNotContain: "å_does not contain_ø",
    stringOperatorIsBlank: "å_is blank_ø",
    stringOperatorIsNotBlank: "å_is not blank_ø",
    dateOperatorIsOn: "å_is on_ø", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "å_is not on_ø",
    dateOperatorIsBefore: "å_is before_ø",
    dateOperatorIsAfter: "å_is after_ø",
    dateOperatorDays: "å_days_ø",
    dateOperatorWeeks: "å_weeks_ø", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "å_months_ø",
    dateOperatorInTheLast: "å_in the last_ø",
    dateOperatorNotInTheLast: "å_not in the last_ø",
    dateOperatorIsBetween: "å_is between_ø",
    dateOperatorIsNotBetween: "å_is not between_ø",
    dateOperatorIsBlank: "å_is blank_ø",
    dateOperatorIsNotBlank: "å_is not blank_ø",
    numberOperatorIs: "å_is_ø", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "å_is not_ø",
    numberOperatorIsAtLeast: "å_is at least_ø",
    numberOperatorIsLessThan: "å_is less than_ø",
    numberOperatorIsAtMost: "å_is at most_ø",
    numberOperatorIsGreaterThan: "å_is greater than_ø",
    numberOperatorIsBetween: "å_is between_ø",
    numberOperatorIsNotBetween: "å_is not between_ø",
    numberOperatorIsBlank: "å_is blank_ø",
    numberOperatorIsNotBlank: "å_is not blank_ø"
});