define({
	root: {
		queries:"Query Tasks",
		addNew: "Add New",
		setSource: "Set Source",
		setQuerySource: "Set",
		name: "Name",
		querySource: "Data Source",
		queryName:"Task Name",
		queryDefinition:"Query Definition",
		resultsSetting:"Results Setting",
		symbolSetting:"Symbol Setting",
		resultSettingTip:"Define display information about the features resulted from the query task.",
		resultItemTitle:"Result Item Title",
		resultItemContent:"Result Item Contents",
		fieldsSetTip:"Check the fields you want to display. Select a field to change its alias, order it and format it.",
		addField:"Add Field",
		visibility:"Visibility",
		alias:"Alias",
		specialType:"Special Type",
		actions:"Actions",
		none:"None",
		link:"Link",
		image:"Image",
		noField:"No field",
		operationalLayerTip:"Add result as operational layer",
		setLayerSymbolTip:"Set symbol for query results: ",
		setSelectedSymbolTip:"Set symbol of selected feature.",
		notUseFilter:"Don't use filter",
		setSourceTip:"Please set query source!",
		setFilterTip:"Please set filter correctly!",
		ok:"OK",
		cancel:"Cancel"
	},
	"ar": false,
	"cs": false,
	"da": false,
	"de": false,
	"es": false,
	"et": false,
	"fi": false,
	"fr": false,
	"he": false,
	"it": false,
	"ja": false,
	"ko": false,
	"lt": false,
	"lv": false,
	"nb": false,
	"nl": false,
	"pl": false,
	"pt-BR": false,
	"pt-PT": false,
	"ro": false,
	"ru": false,
	"sv": false,
	"th": false,
	"tr": false,
	"zh-cn": true
});