define({
  root: {
    execute: "Execute",
    help: "Help",
    input: "Input",
    output: "Output",
    executing: "Executing",
    requiredInfo: "is required.",
    drawnOnMap: "The result is drawn on the map.",
    clear: "Clear"
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": true
});