define({
    executeQueryTip: "Į_Click one of the following items to execute query._š",
    invalidConfig: "Į_Invalid config. Please use Query setting page to get correct config._š",
    queryParams: "Į_Query Parameters_š",
    parameters: "Į_Parameters_š",
    queries: "Į_Queries_š",
    apply: "Į_Apply_š",
    queryResults: "Į_Query Results_š",
    clear: "Į_Clear_š",
    noResults: "Į_No results_š",
    queryError: "Į_Query failed !_š",
    numberFound: "Į_Number of features found_š",
    mapExtentTip:"Į_Limit the results to the current map extent._š",
    noValue:"Į_No value_š",
    and:"Į_and_š",
    friendlyDatePattern:"Į_MM/dd/yyyy_š",
    stringOperatorIs: "Į_is_š", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "Į_is not_š",
    stringOperatorStartsWith: "Į_starts with_š",
    stringOperatorEndsWith: "Į_ends with_š",
    stringOperatorContains: "Į_contains_š",
    stringOperatorDoesNotContain: "Į_does not contain_š",
    stringOperatorIsBlank: "Į_is blank_š",
    stringOperatorIsNotBlank: "Į_is not blank_š",
    dateOperatorIsOn: "Į_is on_š", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "Į_is not on_š",
    dateOperatorIsBefore: "Į_is before_š",
    dateOperatorIsAfter: "Į_is after_š",
    dateOperatorDays: "Į_days_š",
    dateOperatorWeeks: "Į_weeks_š", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "Į_months_š",
    dateOperatorInTheLast: "Į_in the last_š",
    dateOperatorNotInTheLast: "Į_not in the last_š",
    dateOperatorIsBetween: "Į_is between_š",
    dateOperatorIsNotBetween: "Į_is not between_š",
    dateOperatorIsBlank: "Į_is blank_š",
    dateOperatorIsNotBlank: "Į_is not blank_š",
    numberOperatorIs: "Į_is_š", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "Į_is not_š",
    numberOperatorIsAtLeast: "Į_is at least_š",
    numberOperatorIsLessThan: "Į_is less than_š",
    numberOperatorIsAtMost: "Į_is at most_š",
    numberOperatorIsGreaterThan: "Į_is greater than_š",
    numberOperatorIsBetween: "Į_is between_š",
    numberOperatorIsNotBetween: "Į_is not between_š",
    numberOperatorIsBlank: "Į_is blank_š",
    numberOperatorIsNotBlank: "Į_is not blank_š"
});