define({
    taskUrl: "Į_Task URL_š",
    serviceURLPlaceholder: "Į_Please input Geoprocessing task URL_š",
    ok: "Į_OK_š",
    cancel: "Į_Cancel_š",
    layer: "Į_Layer_š",
    action: "Į_Action_š",
    input: "Į_Input_š",
    output: "Į_Output_š",
    name: "Į_Name_š",
    type: "Į_Type_š",
    required: "Į_Required_š",
    layerOrder: "Į_Layer order_š",
    options: "Į_Options_š",
    defaultValue: "Į_Default Value_š",
    inputFeatureBy: "Į_Input Feature by_š",
    renderer: "Į_Renderer_š",
    displayType: "Į_Display type_š",
    label: "Į_Label_š",
    tooltip: "Į_Tooltip_š",
    visible: "Į_Visible_š",
    helpUrl: "Į_Help URL_š",
    useResultMapService: "Į_Use the drawing options of result map service_š",
    drawOnMap: "Į_Interactively drawing on the map_š",
    selectLayer: "Į_Selecting a layer from the map_š",
    url: "Į_URL_š",
    symbol: "Į_Symbol_š",
    shareResults: "Į_Add result as operational layer_š"
});