define({
    taskUrl: "ก้_Task URL_ษฺ",
    serviceURLPlaceholder: "ก้_Please input Geoprocessing task URL_ษฺ",
    ok: "ก้_OK_ษฺ",
    cancel: "ก้_Cancel_ษฺ",
    layer: "ก้_Layer_ษฺ",
    action: "ก้_Action_ษฺ",
    input: "ก้_Input_ษฺ",
    output: "ก้_Output_ษฺ",
    name: "ก้_Name_ษฺ",
    type: "ก้_Type_ษฺ",
    required: "ก้_Required_ษฺ",
    layerOrder: "ก้_Layer order_ษฺ",
    options: "ก้_Options_ษฺ",
    defaultValue: "ก้_Default Value_ษฺ",
    inputFeatureBy: "ก้_Input Feature by_ษฺ",
    renderer: "ก้_Renderer_ษฺ",
    displayType: "ก้_Display type_ษฺ",
    label: "ก้_Label_ษฺ",
    tooltip: "ก้_Tooltip_ษฺ",
    visible: "ก้_Visible_ษฺ",
    helpUrl: "ก้_Help URL_ษฺ",
    useResultMapService: "ก้_Use the drawing options of result map service_ษฺ",
    drawOnMap: "ก้_Interactively drawing on the map_ษฺ",
    selectLayer: "ก้_Selecting a layer from the map_ษฺ",
    url: "ก้_URL_ษฺ",
    symbol: "ก้_Symbol_ษฺ",
    shareResults: "ก้_Add result as operational layer_ษฺ"
});