define({
    ok: "ķ_OK_ū",
    cancel: "ķ_Cancel_ū",
    exportMessage: "ķ_Export data to CSV file?_ū",
    exportFiles: "ķ_Export to CSV_ū",
    options: "ķ_Options_ū",
    zoomto: "ķ_Zoom to_ū",
    highlight: "ķ_Highlight Graphics_ū",
    selectAll: "ķ_Select All Pages_ū",
    selectPage: "ķ_Select Current Page_ū",
    clearSelection: "ķ_Clear Selection_ū",
    filterByExtent: "ķ_Filter by Map Extent_ū",
    refresh: "ķ_Refresh_ū",
    selected: "ķ_selected_ū",
    transparent: "ķ_Transparent Mode_ū",
    indicate: "ķ_Locate Selection_ū",
    columns: "ķ_Show/Hide Columns_ū",
    selectionSymbol: "ķ_Selection Symbol_ū",
    closeMessage: "ķ_Hide table[Show it again in layer list]_ū",
    dataNotAvailable: "ķ_Data not available!<br>Click [Refresh] button to have a try_ū"
});