define({
    ok: "ä_OK_Ü",
    cancel: "ä_Cancel_Ü",
    exportMessage: "ä_Export data to CSV file?_Ü",
    exportFiles: "ä_Export to CSV_Ü",
    options: "ä_Options_Ü",
    zoomto: "ä_Zoom to_Ü",
    highlight: "ä_Highlight Graphics_Ü",
    selectAll: "ä_Select All Pages_Ü",
    selectPage: "ä_Select Current Page_Ü",
    clearSelection: "ä_Clear Selection_Ü",
    filterByExtent: "ä_Filter by Map Extent_Ü",
    refresh: "ä_Refresh_Ü",
    selected: "ä_selected_Ü",
    transparent: "ä_Transparent Mode_Ü",
    indicate: "ä_Locate Selection_Ü",
    columns: "ä_Show/Hide Columns_Ü",
    selectionSymbol: "ä_Selection Symbol_Ü",
    closeMessage: "ä_Hide table[Show it again in layer list]_Ü",
    dataNotAvailable: "ä_Data not available!<br>Click [Refresh] button to have a try_Ü"
});