define({
		queries:"å_Queries_ø",
		addNew: "å_Add New_ø",
		setSource: "å_Set Source_ø",
		setQuerySource: "å_Set query source_ø",
		name: "å_Name_ø",
		querySource: "å_Query Source_ø",
		queryName:"å_Query Name_ø",
		queryDefinition:"å_Query Definition_ø",
		resultsSetting:"å_Results Setting_ø",
		resultSettingTip:"å_Define below for showing information about features that are resulted from the query operation._ø",
		resultItemTitle:"å_Result Item Title_ø",
		resultItemContent:"å_Result Item Content_ø",
		fieldsSetTip:"å_Check the fields you want to display. Select a field to change its alias,order it and format it._ø",
		addField:"å_Add Field_ø",
		visibility:"å_Visibility_ø",
		alias:"å_Alias_ø",
		specialType:"å_Special Type_ø",
		actions:"å_Actions_ø",
		none:"å_None_ø",
		link:"å_Link_ø",
		image:"å_Image_ø",
		noField:"å_No field_ø",
		operationalLayerTip:"å_Add result as operational layer_ø",
		setLayerSymbolTip:"å_Set the symbol of query result._ø",
		setSelectedSymbolTip:"å_Set the symbol of selected feature._ø",
		notUseFilter:"å_Don't use filter_ø",
		setSourceTip:"å_Please set query source !_ø",
		setFilterTip:"å_Please set filter correctly !_ø",
		ok:"å_Ok_ø",
		cancel:"å_Cancel_ø"
});