define({
    ok: "确定",
    cancel: "取消",
    exportMessage: "将数据导出成CSV文件？",
    exportFiles: "导出为CSV文件",
    options: "选项",
    zoomto: "缩放到",
    highlight: "高亮所选要素",
    selectAll: "选中所有要素",
    selectPage: "选中当前页要素",
    clearSelection: "清除选择",
    filterByExtent: "根据地图范围进行过滤",
    refresh: "刷新",
    selected: "选中的",
    transparent: "透明模式",
    indicate: "定位到所选记录",
    columns: "显示/隐藏 字段",
    selectionSymbol: "选中要素符号",
    closeMessage: "隐藏属性表(可从页面底部打开)",
    dataNotAvailable: "数据不可用！<br>点击[刷新]按钮进行重试。",
    openTableTip: "打开属性表",
    closeTableTip: "隐藏属性表"
  });