define({
    executeQueryTip: "Ж_Click one of the following items to execute query._Я",
    invalidConfig: "Ж_Invalid config. Please use Query setting page to get correct config._Я",
    queryParams: "Ж_Query Parameters_Я",
    parameters: "Ж_Parameters_Я",
    queries: "Ж_Queries_Я",
    apply: "Ж_Apply_Я",
    queryResults: "Ж_Query Results_Я",
    clear: "Ж_Clear_Я",
    noResults: "Ж_No results_Я",
    queryError: "Ж_Query failed !_Я",
    numberFound: "Ж_Number of features found_Я",
    mapExtentTip:"Ж_Limit the results to the current map extent._Я",
    noValue:"Ж_No value_Я",
    and:"Ж_and_Я",
    friendlyDatePattern:"Ж_MM/dd/yyyy_Я",
    stringOperatorIs: "Ж_is_Я", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "Ж_is not_Я",
    stringOperatorStartsWith: "Ж_starts with_Я",
    stringOperatorEndsWith: "Ж_ends with_Я",
    stringOperatorContains: "Ж_contains_Я",
    stringOperatorDoesNotContain: "Ж_does not contain_Я",
    stringOperatorIsBlank: "Ж_is blank_Я",
    stringOperatorIsNotBlank: "Ж_is not blank_Я",
    dateOperatorIsOn: "Ж_is on_Я", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "Ж_is not on_Я",
    dateOperatorIsBefore: "Ж_is before_Я",
    dateOperatorIsAfter: "Ж_is after_Я",
    dateOperatorDays: "Ж_days_Я",
    dateOperatorWeeks: "Ж_weeks_Я", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "Ж_months_Я",
    dateOperatorInTheLast: "Ж_in the last_Я",
    dateOperatorNotInTheLast: "Ж_not in the last_Я",
    dateOperatorIsBetween: "Ж_is between_Я",
    dateOperatorIsNotBetween: "Ж_is not between_Я",
    dateOperatorIsBlank: "Ж_is blank_Я",
    dateOperatorIsNotBlank: "Ж_is not blank_Я",
    numberOperatorIs: "Ж_is_Я", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "Ж_is not_Я",
    numberOperatorIsAtLeast: "Ж_is at least_Я",
    numberOperatorIsLessThan: "Ж_is less than_Я",
    numberOperatorIsAtMost: "Ж_is at most_Я",
    numberOperatorIsGreaterThan: "Ж_is greater than_Я",
    numberOperatorIsBetween: "Ж_is between_Я",
    numberOperatorIsNotBetween: "Ж_is not between_Я",
    numberOperatorIsBlank: "Ж_is blank_Я",
    numberOperatorIsNotBlank: "Ж_is not blank_Я"
});