define({
    ok: "ı_OK_İ",
    cancel: "ı_Cancel_İ",
    exportMessage: "ı_Export data to CSV file?_İ",
    exportFiles: "ı_Export to CSV_İ",
    options: "ı_Options_İ",
    zoomto: "ı_Zoom to_İ",
    highlight: "ı_Highlight Graphics_İ",
    selectAll: "ı_Select All Pages_İ",
    selectPage: "ı_Select Current Page_İ",
    clearSelection: "ı_Clear Selection_İ",
    filterByExtent: "ı_Filter by Map Extent_İ",
    refresh: "ı_Refresh_İ",
    selected: "ı_selected_İ",
    transparent: "ı_Transparent Mode_İ",
    indicate: "ı_Locate Selection_İ",
    columns: "ı_Show/Hide Columns_İ",
    selectionSymbol: "ı_Selection Symbol_İ",
    closeMessage: "ı_Hide table[Show it again in layer list]_İ",
    dataNotAvailable: "ı_Data not available!<br>Click [Refresh] button to have a try_İ"
});