define({
    executeQueryTip: "á_Click one of the following items to execute query._Ó",
    invalidConfig: "á_Invalid config. Please use Query setting page to get correct config._Ó",
    queryParams: "á_Query Parameters_Ó",
    parameters: "á_Parameters_Ó",
    queries: "á_Queries_Ó",
    apply: "á_Apply_Ó",
    queryResults: "á_Query Results_Ó",
    clear: "á_Clear_Ó",
    noResults: "á_No results_Ó",
    queryError: "á_Query failed !_Ó",
    numberFound: "á_Number of features found_Ó",
    mapExtentTip:"á_Limit the results to the current map extent._Ó",
    noValue:"á_No value_Ó",
    and:"á_and_Ó",
    friendlyDatePattern:"á_MM/dd/yyyy_Ó",
    stringOperatorIs: "á_is_Ó", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "á_is not_Ó",
    stringOperatorStartsWith: "á_starts with_Ó",
    stringOperatorEndsWith: "á_ends with_Ó",
    stringOperatorContains: "á_contains_Ó",
    stringOperatorDoesNotContain: "á_does not contain_Ó",
    stringOperatorIsBlank: "á_is blank_Ó",
    stringOperatorIsNotBlank: "á_is not blank_Ó",
    dateOperatorIsOn: "á_is on_Ó", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "á_is not on_Ó",
    dateOperatorIsBefore: "á_is before_Ó",
    dateOperatorIsAfter: "á_is after_Ó",
    dateOperatorDays: "á_days_Ó",
    dateOperatorWeeks: "á_weeks_Ó", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "á_months_Ó",
    dateOperatorInTheLast: "á_in the last_Ó",
    dateOperatorNotInTheLast: "á_not in the last_Ó",
    dateOperatorIsBetween: "á_is between_Ó",
    dateOperatorIsNotBetween: "á_is not between_Ó",
    dateOperatorIsBlank: "á_is blank_Ó",
    dateOperatorIsNotBlank: "á_is not blank_Ó",
    numberOperatorIs: "á_is_Ó", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "á_is not_Ó",
    numberOperatorIsAtLeast: "á_is at least_Ó",
    numberOperatorIsLessThan: "á_is less than_Ó",
    numberOperatorIsAtMost: "á_is at most_Ó",
    numberOperatorIsGreaterThan: "á_is greater than_Ó",
    numberOperatorIsBetween: "á_is between_Ó",
    numberOperatorIsNotBetween: "á_is not between_Ó",
    numberOperatorIsBlank: "á_is blank_Ó",
    numberOperatorIsNotBlank: "á_is not blank_Ó"
});