define({
    taskUrl: "å_Task URL_ø",
    serviceURLPlaceholder: "å_Please input Geoprocessing task URL_ø",
    ok: "å_OK_ø",
    cancel: "å_Cancel_ø",
    layer: "å_Layer_ø",
    action: "å_Action_ø",
    input: "å_Input_ø",
    output: "å_Output_ø",
    name: "å_Name_ø",
    type: "å_Type_ø",
    required: "å_Required_ø",
    layerOrder: "å_Layer order_ø",
    options: "å_Options_ø",
    defaultValue: "å_Default Value_ø",
    inputFeatureBy: "å_Input Feature by_ø",
    renderer: "å_Renderer_ø",
    displayType: "å_Display type_ø",
    label: "å_Label_ø",
    tooltip: "å_Tooltip_ø",
    visible: "å_Visible_ø",
    helpUrl: "å_Help URL_ø",
    useResultMapService: "å_Use the drawing options of result map service_ø",
    drawOnMap: "å_Interactively drawing on the map_ø",
    selectLayer: "å_Selecting a layer from the map_ø",
    url: "å_URL_ø",
    symbol: "å_Symbol_ø",
    shareResults: "å_Add result as operational layer_ø"
});