define({
    executeQueryTip: "ł_Click one of the following items to execute query._ą",
    invalidConfig: "ł_Invalid config. Please use Query setting page to get correct config._ą",
    queryParams: "ł_Query Parameters_ą",
    parameters: "ł_Parameters_ą",
    queries: "ł_Queries_ą",
    apply: "ł_Apply_ą",
    queryResults: "ł_Query Results_ą",
    clear: "ł_Clear_ą",
    noResults: "ł_No results_ą",
    queryError: "ł_Query failed !_ą",
    numberFound: "ł_Number of features found_ą",
    mapExtentTip:"ł_Limit the results to the current map extent._ą",
    noValue:"ł_No value_ą",
    and:"ł_and_ą",
    friendlyDatePattern:"ł_MM/dd/yyyy_ą",
    stringOperatorIs: "ł_is_ą", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "ł_is not_ą",
    stringOperatorStartsWith: "ł_starts with_ą",
    stringOperatorEndsWith: "ł_ends with_ą",
    stringOperatorContains: "ł_contains_ą",
    stringOperatorDoesNotContain: "ł_does not contain_ą",
    stringOperatorIsBlank: "ł_is blank_ą",
    stringOperatorIsNotBlank: "ł_is not blank_ą",
    dateOperatorIsOn: "ł_is on_ą", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "ł_is not on_ą",
    dateOperatorIsBefore: "ł_is before_ą",
    dateOperatorIsAfter: "ł_is after_ą",
    dateOperatorDays: "ł_days_ą",
    dateOperatorWeeks: "ł_weeks_ą", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "ł_months_ą",
    dateOperatorInTheLast: "ł_in the last_ą",
    dateOperatorNotInTheLast: "ł_not in the last_ą",
    dateOperatorIsBetween: "ł_is between_ą",
    dateOperatorIsNotBetween: "ł_is not between_ą",
    dateOperatorIsBlank: "ł_is blank_ą",
    dateOperatorIsNotBlank: "ł_is not blank_ą",
    numberOperatorIs: "ł_is_ą", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "ł_is not_ą",
    numberOperatorIsAtLeast: "ł_is at least_ą",
    numberOperatorIsLessThan: "ł_is less than_ą",
    numberOperatorIsAtMost: "ł_is at most_ą",
    numberOperatorIsGreaterThan: "ł_is greater than_ą",
    numberOperatorIsBetween: "ł_is between_ą",
    numberOperatorIsNotBetween: "ł_is not between_ą",
    numberOperatorIsBlank: "ł_is blank_ą",
    numberOperatorIsNotBlank: "ł_is not blank_ą"
});