define({
		queries:"Å_Queries_ö",
		addNew: "Å_Add New_ö",
		setSource: "Å_Set Source_ö",
		setQuerySource: "Å_Set query source_ö",
		name: "Å_Name_ö",
		querySource: "Å_Query Source_ö",
		queryName:"Å_Query Name_ö",
		queryDefinition:"Å_Query Definition_ö",
		resultsSetting:"Å_Results Setting_ö",
		resultSettingTip:"Å_Define below for showing information about features that are resulted from the query operation._ö",
		resultItemTitle:"Å_Result Item Title_ö",
		resultItemContent:"Å_Result Item Content_ö",
		fieldsSetTip:"Å_Check the fields you want to display. Select a field to change its alias,order it and format it._ö",
		addField:"Å_Add Field_ö",
		visibility:"Å_Visibility_ö",
		alias:"Å_Alias_ö",
		specialType:"Å_Special Type_ö",
		actions:"Å_Actions_ö",
		none:"Å_None_ö",
		link:"Å_Link_ö",
		image:"Å_Image_ö",
		noField:"Å_No field_ö",
		operationalLayerTip:"Å_Add result as operational layer_ö",
		setLayerSymbolTip:"Å_Set the symbol of query result._ö",
		setSelectedSymbolTip:"Å_Set the symbol of selected feature._ö",
		notUseFilter:"Å_Don't use filter_ö",
		setSourceTip:"Å_Please set query source !_ö",
		setFilterTip:"Å_Please set filter correctly !_ö",
		ok:"Å_Ok_ö",
		cancel:"Å_Cancel_ö"
});