define({
    taskUrl: "ã_Task URL_Ç",
    serviceURLPlaceholder: "ã_Please input Geoprocessing task URL_Ç",
    ok: "ã_OK_Ç",
    cancel: "ã_Cancel_Ç",
    layer: "ã_Layer_Ç",
    action: "ã_Action_Ç",
    input: "ã_Input_Ç",
    output: "ã_Output_Ç",
    name: "ã_Name_Ç",
    type: "ã_Type_Ç",
    required: "ã_Required_Ç",
    layerOrder: "ã_Layer order_Ç",
    options: "ã_Options_Ç",
    defaultValue: "ã_Default Value_Ç",
    inputFeatureBy: "ã_Input Feature by_Ç",
    renderer: "ã_Renderer_Ç",
    displayType: "ã_Display type_Ç",
    label: "ã_Label_Ç",
    tooltip: "ã_Tooltip_Ç",
    visible: "ã_Visible_Ç",
    helpUrl: "ã_Help URL_Ç",
    useResultMapService: "ã_Use the drawing options of result map service_Ç",
    drawOnMap: "ã_Interactively drawing on the map_Ç",
    selectLayer: "ã_Selecting a layer from the map_Ç",
    url: "ã_URL_Ç",
    symbol: "ã_Symbol_Ç",
    shareResults: "ã_Add result as operational layer_Ç"
});