define({
    executeQueryTip: "ã_Click one of the following items to execute query._Ç",
    invalidConfig: "ã_Invalid config. Please use Query setting page to get correct config._Ç",
    queryParams: "ã_Query Parameters_Ç",
    parameters: "ã_Parameters_Ç",
    queries: "ã_Queries_Ç",
    apply: "ã_Apply_Ç",
    queryResults: "ã_Query Results_Ç",
    clear: "ã_Clear_Ç",
    noResults: "ã_No results_Ç",
    queryError: "ã_Query failed !_Ç",
    numberFound: "ã_Number of features found_Ç",
    mapExtentTip:"ã_Limit the results to the current map extent._Ç",
    noValue:"ã_No value_Ç",
    and:"ã_and_Ç",
    friendlyDatePattern:"ã_MM/dd/yyyy_Ç",
    stringOperatorIs: "ã_is_Ç", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "ã_is not_Ç",
    stringOperatorStartsWith: "ã_starts with_Ç",
    stringOperatorEndsWith: "ã_ends with_Ç",
    stringOperatorContains: "ã_contains_Ç",
    stringOperatorDoesNotContain: "ã_does not contain_Ç",
    stringOperatorIsBlank: "ã_is blank_Ç",
    stringOperatorIsNotBlank: "ã_is not blank_Ç",
    dateOperatorIsOn: "ã_is on_Ç", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "ã_is not on_Ç",
    dateOperatorIsBefore: "ã_is before_Ç",
    dateOperatorIsAfter: "ã_is after_Ç",
    dateOperatorDays: "ã_days_Ç",
    dateOperatorWeeks: "ã_weeks_Ç", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "ã_months_Ç",
    dateOperatorInTheLast: "ã_in the last_Ç",
    dateOperatorNotInTheLast: "ã_not in the last_Ç",
    dateOperatorIsBetween: "ã_is between_Ç",
    dateOperatorIsNotBetween: "ã_is not between_Ç",
    dateOperatorIsBlank: "ã_is blank_Ç",
    dateOperatorIsNotBlank: "ã_is not blank_Ç",
    numberOperatorIs: "ã_is_Ç", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "ã_is not_Ç",
    numberOperatorIsAtLeast: "ã_is at least_Ç",
    numberOperatorIsLessThan: "ã_is less than_Ç",
    numberOperatorIsAtMost: "ã_is at most_Ç",
    numberOperatorIsGreaterThan: "ã_is greater than_Ç",
    numberOperatorIsBetween: "ã_is between_Ç",
    numberOperatorIsNotBetween: "ã_is not between_Ç",
    numberOperatorIsBlank: "ã_is blank_Ç",
    numberOperatorIsNotBlank: "ã_is not blank_Ç"
});