define({
    showArcgisBasemaps: "ä_Show ArcGIS Basemaps_Ü",
    add: "ä_Click to add a new basemap_Ü",
    edit: "ä_Properties_Ü",
    title: "ä_Title_Ü",
    thumbnail: "ä_Thumbnail_Ü",
    thumbnailHint: "ä_Click image to update_Ü",
    url: "ä_URL_Ü",
    addlayer: "ä_Add layer_Ü",
    actions: "ä_Actions_Ü",
    warning: "ä_Incorrect input_Ü",
    save: "ä_Back and Save_Ü",
    back: "ä_Back and Cancel_Ü",
    addUrl: "ä_Add URL_Ü",
    autoCheck: "ä_Auto Check_Ü",
    checking: "ä_Checking..._Ü",
    ok: "ä_OK_Ü",
    cancel: "ä_Cancel_Ü",
    result: "ä_Save successfully_Ü",
    spError: "ä_All basemaps added to the gallery need to have the same spatial reference._Ü"
});