define({
		queries:"Ă_Queries_ș",
		addNew: "Ă_Add New_ș",
		setSource: "Ă_Set Source_ș",
		setQuerySource: "Ă_Set query source_ș",
		name: "Ă_Name_ș",
		querySource: "Ă_Query Source_ș",
		queryName:"Ă_Query Name_ș",
		queryDefinition:"Ă_Query Definition_ș",
		resultsSetting:"Ă_Results Setting_ș",
		resultSettingTip:"Ă_Define below for showing information about features that are resulted from the query operation._ș",
		resultItemTitle:"Ă_Result Item Title_ș",
		resultItemContent:"Ă_Result Item Content_ș",
		fieldsSetTip:"Ă_Check the fields you want to display. Select a field to change its alias,order it and format it._ș",
		addField:"Ă_Add Field_ș",
		visibility:"Ă_Visibility_ș",
		alias:"Ă_Alias_ș",
		specialType:"Ă_Special Type_ș",
		actions:"Ă_Actions_ș",
		none:"Ă_None_ș",
		link:"Ă_Link_ș",
		image:"Ă_Image_ș",
		noField:"Ă_No field_ș",
		operationalLayerTip:"Ă_Add result as operational layer_ș",
		setLayerSymbolTip:"Ă_Set the symbol of query result._ș",
		setSelectedSymbolTip:"Ă_Set the symbol of selected feature._ș",
		notUseFilter:"Ă_Don't use filter_ș",
		setSourceTip:"Ă_Please set query source !_ș",
		setFilterTip:"Ă_Please set filter correctly !_ș",
		ok:"Ă_Ok_ș",
		cancel:"Ă_Cancel_ș"
});