define({
    taskUrl: "بيت_Task URL_لاحقة",
    serviceURLPlaceholder: "بيت_Please input Geoprocessing task URL_لاحقة",
    ok: "بيت_OK_لاحقة",
    cancel: "بيت_Cancel_لاحقة",
    layer: "بيت_Layer_لاحقة",
    action: "بيت_Action_لاحقة",
    input: "بيت_Input_لاحقة",
    output: "بيت_Output_لاحقة",
    name: "بيت_Name_لاحقة",
    type: "بيت_Type_لاحقة",
    required: "بيت_Required_لاحقة",
    layerOrder: "بيت_Layer order_لاحقة",
    options: "بيت_Options_لاحقة",
    defaultValue: "بيت_Default Value_لاحقة",
    inputFeatureBy: "بيت_Input Feature by_لاحقة",
    renderer: "بيت_Renderer_لاحقة",
    displayType: "بيت_Display type_لاحقة",
    label: "بيت_Label_لاحقة",
    tooltip: "بيت_Tooltip_لاحقة",
    visible: "بيت_Visible_لاحقة",
    helpUrl: "بيت_Help URL_لاحقة",
    useResultMapService: "بيت_Use the drawing options of result map service_لاحقة",
    drawOnMap: "بيت_Interactively drawing on the map_لاحقة",
    selectLayer: "بيت_Selecting a layer from the map_لاحقة",
    url: "بيت_URL_لاحقة",
    symbol: "بيت_Symbol_لاحقة",
    shareResults: "بيت_Add result as operational layer_لاحقة"
});