define({
    showArcgisBasemaps: "ķ_Show ArcGIS Basemaps_ū",
    add: "ķ_Click to add a new basemap_ū",
    edit: "ķ_Properties_ū",
    title: "ķ_Title_ū",
    thumbnail: "ķ_Thumbnail_ū",
    thumbnailHint: "ķ_Click image to update_ū",
    url: "ķ_URL_ū",
    addlayer: "ķ_Add layer_ū",
    actions: "ķ_Actions_ū",
    warning: "ķ_Incorrect input_ū",
    save: "ķ_Back and Save_ū",
    back: "ķ_Back and Cancel_ū",
    addUrl: "ķ_Add URL_ū",
    autoCheck: "ķ_Auto Check_ū",
    checking: "ķ_Checking..._ū",
    ok: "ķ_OK_ū",
    cancel: "ķ_Cancel_ū",
    result: "ķ_Save successfully_ū",
    spError: "ķ_All basemaps added to the gallery need to have the same spatial reference._ū"
});