define({
    executeQueryTip: "ı_Click one of the following items to execute query._İ",
    invalidConfig: "ı_Invalid config. Please use Query setting page to get correct config._İ",
    queryParams: "ı_Query Parameters_İ",
    parameters: "ı_Parameters_İ",
    queries: "ı_Queries_İ",
    apply: "ı_Apply_İ",
    queryResults: "ı_Query Results_İ",
    clear: "ı_Clear_İ",
    noResults: "ı_No results_İ",
    queryError: "ı_Query failed !_İ",
    numberFound: "ı_Number of features found_İ",
    mapExtentTip:"ı_Limit the results to the current map extent._İ",
    noValue:"ı_No value_İ",
    and:"ı_and_İ",
    friendlyDatePattern:"ı_MM/dd/yyyy_İ",
    stringOperatorIs: "ı_is_İ", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "ı_is not_İ",
    stringOperatorStartsWith: "ı_starts with_İ",
    stringOperatorEndsWith: "ı_ends with_İ",
    stringOperatorContains: "ı_contains_İ",
    stringOperatorDoesNotContain: "ı_does not contain_İ",
    stringOperatorIsBlank: "ı_is blank_İ",
    stringOperatorIsNotBlank: "ı_is not blank_İ",
    dateOperatorIsOn: "ı_is on_İ", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "ı_is not on_İ",
    dateOperatorIsBefore: "ı_is before_İ",
    dateOperatorIsAfter: "ı_is after_İ",
    dateOperatorDays: "ı_days_İ",
    dateOperatorWeeks: "ı_weeks_İ", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "ı_months_İ",
    dateOperatorInTheLast: "ı_in the last_İ",
    dateOperatorNotInTheLast: "ı_not in the last_İ",
    dateOperatorIsBetween: "ı_is between_İ",
    dateOperatorIsNotBetween: "ı_is not between_İ",
    dateOperatorIsBlank: "ı_is blank_İ",
    dateOperatorIsNotBlank: "ı_is not blank_İ",
    numberOperatorIs: "ı_is_İ", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "ı_is not_İ",
    numberOperatorIsAtLeast: "ı_is at least_İ",
    numberOperatorIsLessThan: "ı_is less than_İ",
    numberOperatorIsAtMost: "ı_is at most_İ",
    numberOperatorIsGreaterThan: "ı_is greater than_İ",
    numberOperatorIsBetween: "ı_is between_İ",
    numberOperatorIsNotBetween: "ı_is not between_İ",
    numberOperatorIsBlank: "ı_is blank_İ",
    numberOperatorIsNotBlank: "ı_is not blank_İ"
});