define({
    taskUrl: "Ĳ_Task URL_ä",
    serviceURLPlaceholder: "Ĳ_Please input Geoprocessing task URL_ä",
    ok: "Ĳ_OK_ä",
    cancel: "Ĳ_Cancel_ä",
    layer: "Ĳ_Layer_ä",
    action: "Ĳ_Action_ä",
    input: "Ĳ_Input_ä",
    output: "Ĳ_Output_ä",
    name: "Ĳ_Name_ä",
    type: "Ĳ_Type_ä",
    required: "Ĳ_Required_ä",
    layerOrder: "Ĳ_Layer order_ä",
    options: "Ĳ_Options_ä",
    defaultValue: "Ĳ_Default Value_ä",
    inputFeatureBy: "Ĳ_Input Feature by_ä",
    renderer: "Ĳ_Renderer_ä",
    displayType: "Ĳ_Display type_ä",
    label: "Ĳ_Label_ä",
    tooltip: "Ĳ_Tooltip_ä",
    visible: "Ĳ_Visible_ä",
    helpUrl: "Ĳ_Help URL_ä",
    useResultMapService: "Ĳ_Use the drawing options of result map service_ä",
    drawOnMap: "Ĳ_Interactively drawing on the map_ä",
    selectLayer: "Ĳ_Selecting a layer from the map_ä",
    url: "Ĳ_URL_ä",
    symbol: "Ĳ_Symbol_ä",
    shareResults: "Ĳ_Add result as operational layer_ä"
});