define({
    taskUrl: "한_Task URL_빠",
    serviceURLPlaceholder: "한_Please input Geoprocessing task URL_빠",
    ok: "한_OK_빠",
    cancel: "한_Cancel_빠",
    layer: "한_Layer_빠",
    action: "한_Action_빠",
    input: "한_Input_빠",
    output: "한_Output_빠",
    name: "한_Name_빠",
    type: "한_Type_빠",
    required: "한_Required_빠",
    layerOrder: "한_Layer order_빠",
    options: "한_Options_빠",
    defaultValue: "한_Default Value_빠",
    inputFeatureBy: "한_Input Feature by_빠",
    renderer: "한_Renderer_빠",
    displayType: "한_Display type_빠",
    label: "한_Label_빠",
    tooltip: "한_Tooltip_빠",
    visible: "한_Visible_빠",
    helpUrl: "한_Help URL_빠",
    useResultMapService: "한_Use the drawing options of result map service_빠",
    drawOnMap: "한_Interactively drawing on the map_빠",
    selectLayer: "한_Selecting a layer from the map_빠",
    url: "한_URL_빠",
    symbol: "한_Symbol_빠",
    shareResults: "한_Add result as operational layer_빠"
});