define({
    ok: "Ř_OK_ů",
    cancel: "Ř_Cancel_ů",
    exportMessage: "Ř_Export data to CSV file?_ů",
    exportFiles: "Ř_Export to CSV_ů",
    options: "Ř_Options_ů",
    zoomto: "Ř_Zoom to_ů",
    highlight: "Ř_Highlight Graphics_ů",
    selectAll: "Ř_Select All Pages_ů",
    selectPage: "Ř_Select Current Page_ů",
    clearSelection: "Ř_Clear Selection_ů",
    filterByExtent: "Ř_Filter by Map Extent_ů",
    refresh: "Ř_Refresh_ů",
    selected: "Ř_selected_ů",
    transparent: "Ř_Transparent Mode_ů",
    indicate: "Ř_Locate Selection_ů",
    columns: "Ř_Show/Hide Columns_ů",
    selectionSymbol: "Ř_Selection Symbol_ů",
    closeMessage: "Ř_Hide table[Show it again in layer list]_ů",
    dataNotAvailable: "Ř_Data not available!<br>Click [Refresh] button to have a try_ů"
});