define({
		queries:"بيت_Queries_لاحقة",
		addNew: "بيت_Add New_لاحقة",
		setSource: "بيت_Set Source_لاحقة",
		setQuerySource: "بيت_Set query source_لاحقة",
		name: "بيت_Name_لاحقة",
		querySource: "بيت_Query Source_لاحقة",
		queryName:"بيت_Query Name_لاحقة",
		queryDefinition:"بيت_Query Definition_لاحقة",
		resultsSetting:"بيت_Results Setting_لاحقة",
		resultSettingTip:"بيت_Define below for showing information about features that are resulted from the query operation._لاحقة",
		resultItemTitle:"بيت_Result Item Title_لاحقة",
		resultItemContent:"بيت_Result Item Content_لاحقة",
		fieldsSetTip:"بيت_Check the fields you want to display. Select a field to change its alias,order it and format it._لاحقة",
		addField:"بيت_Add Field_لاحقة",
		visibility:"بيت_Visibility_لاحقة",
		alias:"بيت_Alias_لاحقة",
		specialType:"بيت_Special Type_لاحقة",
		actions:"بيت_Actions_لاحقة",
		none:"بيت_None_لاحقة",
		link:"بيت_Link_لاحقة",
		image:"بيت_Image_لاحقة",
		noField:"بيت_No field_لاحقة",
		operationalLayerTip:"بيت_Add result as operational layer_لاحقة",
		setLayerSymbolTip:"بيت_Set the symbol of query result._لاحقة",
		setSelectedSymbolTip:"بيت_Set the symbol of selected feature._لاحقة",
		notUseFilter:"بيت_Don't use filter_لاحقة",
		setSourceTip:"بيت_Please set query source !_لاحقة",
		setFilterTip:"بيت_Please set filter correctly !_لاحقة",
		ok:"بيت_Ok_لاحقة",
		cancel:"بيت_Cancel_لاحقة"
});