define({
  root: {
    label: "Layer",
    show: "Show",
    actions: "Selection Symbol",
    field: "Field",
    alias: "Alias",
    visible: "Visible",
    linkField: "Link Field",
    noLayers: "No feature layers available",
    back: "Back",
    exportCSV: "Allow exporting to CSV",
    restore: "Restore to default value",
    ok: "OK",
    result: "Saved successfully",
    warning: "Check to show this layer in table first most."
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": true
});