define({
    showArcgisBasemaps: "é_Show ArcGIS Basemaps_È",
    add: "é_Click to add a new basemap_È",
    edit: "é_Properties_È",
    title: "é_Title_È",
    thumbnail: "é_Thumbnail_È",
    thumbnailHint: "é_Click image to update_È",
    url: "é_URL_È",
    addlayer: "é_Add layer_È",
    actions: "é_Actions_È",
    warning: "é_Incorrect input_È",
    save: "é_Back and Save_È",
    back: "é_Back and Cancel_È",
    addUrl: "é_Add URL_È",
    autoCheck: "é_Auto Check_È",
    checking: "é_Checking..._È",
    ok: "é_OK_È",
    cancel: "é_Cancel_È",
    result: "é_Save successfully_È",
    spError: "é_All basemaps added to the gallery need to have the same spatial reference._È"
});