define({
  root: {
    labelBookmarkName: "Bookmark the current view",
    labelPlay: "Play All",
    labelStop: "Stop",
    labelDelete: "Delete",
    placeholderBookmarkName: "Bookmark Name",
    errorNameExist: "Bookmark exists!",
    errorNameNull: "Invalid bookmark name!"
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": true
});