define({
    executeQueryTip: "Š_Click one of the following items to execute query._ä",
    invalidConfig: "Š_Invalid config. Please use Query setting page to get correct config._ä",
    queryParams: "Š_Query Parameters_ä",
    parameters: "Š_Parameters_ä",
    queries: "Š_Queries_ä",
    apply: "Š_Apply_ä",
    queryResults: "Š_Query Results_ä",
    clear: "Š_Clear_ä",
    noResults: "Š_No results_ä",
    queryError: "Š_Query failed !_ä",
    numberFound: "Š_Number of features found_ä",
    mapExtentTip:"Š_Limit the results to the current map extent._ä",
    noValue:"Š_No value_ä",
    and:"Š_and_ä",
    friendlyDatePattern:"Š_MM/dd/yyyy_ä",
    stringOperatorIs: "Š_is_ä", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "Š_is not_ä",
    stringOperatorStartsWith: "Š_starts with_ä",
    stringOperatorEndsWith: "Š_ends with_ä",
    stringOperatorContains: "Š_contains_ä",
    stringOperatorDoesNotContain: "Š_does not contain_ä",
    stringOperatorIsBlank: "Š_is blank_ä",
    stringOperatorIsNotBlank: "Š_is not blank_ä",
    dateOperatorIsOn: "Š_is on_ä", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "Š_is not on_ä",
    dateOperatorIsBefore: "Š_is before_ä",
    dateOperatorIsAfter: "Š_is after_ä",
    dateOperatorDays: "Š_days_ä",
    dateOperatorWeeks: "Š_weeks_ä", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "Š_months_ä",
    dateOperatorInTheLast: "Š_in the last_ä",
    dateOperatorNotInTheLast: "Š_not in the last_ä",
    dateOperatorIsBetween: "Š_is between_ä",
    dateOperatorIsNotBetween: "Š_is not between_ä",
    dateOperatorIsBlank: "Š_is blank_ä",
    dateOperatorIsNotBlank: "Š_is not blank_ä",
    numberOperatorIs: "Š_is_ä", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "Š_is not_ä",
    numberOperatorIsAtLeast: "Š_is at least_ä",
    numberOperatorIsLessThan: "Š_is less than_ä",
    numberOperatorIsAtMost: "Š_is at most_ä",
    numberOperatorIsGreaterThan: "Š_is greater than_ä",
    numberOperatorIsBetween: "Š_is between_ä",
    numberOperatorIsNotBetween: "Š_is not between_ä",
    numberOperatorIsBlank: "Š_is blank_ä",
    numberOperatorIsNotBlank: "Š_is not blank_ä"
});