define({
    taskUrl: "æ_Task URL_Â",
    serviceURLPlaceholder: "æ_Please input Geoprocessing task URL_Â",
    ok: "æ_OK_Â",
    cancel: "æ_Cancel_Â",
    layer: "æ_Layer_Â",
    action: "æ_Action_Â",
    input: "æ_Input_Â",
    output: "æ_Output_Â",
    name: "æ_Name_Â",
    type: "æ_Type_Â",
    required: "æ_Required_Â",
    layerOrder: "æ_Layer order_Â",
    options: "æ_Options_Â",
    defaultValue: "æ_Default Value_Â",
    inputFeatureBy: "æ_Input Feature by_Â",
    renderer: "æ_Renderer_Â",
    displayType: "æ_Display type_Â",
    label: "æ_Label_Â",
    tooltip: "æ_Tooltip_Â",
    visible: "æ_Visible_Â",
    helpUrl: "æ_Help URL_Â",
    useResultMapService: "æ_Use the drawing options of result map service_Â",
    drawOnMap: "æ_Interactively drawing on the map_Â",
    selectLayer: "æ_Selecting a layer from the map_Â",
    url: "æ_URL_Â",
    symbol: "æ_Symbol_Â",
    shareResults: "æ_Add result as operational layer_Â"
});