define({
    executeQueryTip: "点击以下任务执行查询：",
    invalidConfig: "无效的配置。请通过这个工具的配置对话框进行配置。",
    queryParams: "选项",
    parameters: "选项",
    queries: "查询",
    apply: "应用",
    queryResults: "结果",
    clear: "清除",
    noResults: "没有找到要素。",
    queryError: "查询失败!",
    numberFound: "查询到的要素数量 ",
    mapExtentTip:"Limit the results to the current map extent.",
    noValue:"没有值",
    and:"和",
    friendlyDatePattern:"月/日/年",
    stringOperatorIs: "是", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "不是",
    stringOperatorStartsWith: "开头是",
    stringOperatorEndsWith: "结尾是",
    stringOperatorContains: "包含",
    stringOperatorDoesNotContain: "不包含",
    stringOperatorIsBlank: "为空",
    stringOperatorIsNotBlank: "不为空",
    dateOperatorIsOn: "在", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "不在",
    dateOperatorIsBefore: "早于",
    dateOperatorIsAfter: "晚于",
    dateOperatorDays: "天",
    dateOperatorWeeks: "周", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "月",
    dateOperatorInTheLast: "最后",
    dateOperatorNotInTheLast: "不是最后",
    dateOperatorIsBetween: "介于",
    dateOperatorIsNotBetween: "不介于",
    dateOperatorIsBlank: "为空",
    dateOperatorIsNotBlank: "不为空",
    numberOperatorIs: "等于", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "不等于",
    numberOperatorIsAtLeast: "最小为",
    numberOperatorIsLessThan: "小于",
    numberOperatorIsAtMost: "最大为",
    numberOperatorIsGreaterThan: "大于",
    numberOperatorIsBetween: "介于",
    numberOperatorIsNotBetween: "不介于",
    numberOperatorIsBlank: "为空",
    numberOperatorIsNotBlank: "不为空",
    operationalLayerTip:"将结果添加为业务图层",
    queryResult:"查询结果",
    specifyParamsTip:"为这个查询任务指定参数",
    useSpatialFilter:"启用空间范围过滤",
    useCurrentMapExtent:"使用当前地图范围",
    drawGraphicOnMap:"在地图上绘制图形",
    specifySpatialFilterMsg:"请为此查询任务指定空间过滤范围。",
    clearResults: "清除结果",
    operationalTip:'该选项被选中后，查询到的要素将会一直显示在地图上，直到点击 "${clearResults}" 按钮。',
    noneQueryTip:"暂无可用的查询任务。请联系应用创建者进行配置。",
    noPermissionsMsg:"你没有权限访问这个服务。"
});