define({
    taskUrl: "Ă_Task URL_ș",
    serviceURLPlaceholder: "Ă_Please input Geoprocessing task URL_ș",
    ok: "Ă_OK_ș",
    cancel: "Ă_Cancel_ș",
    layer: "Ă_Layer_ș",
    action: "Ă_Action_ș",
    input: "Ă_Input_ș",
    output: "Ă_Output_ș",
    name: "Ă_Name_ș",
    type: "Ă_Type_ș",
    required: "Ă_Required_ș",
    layerOrder: "Ă_Layer order_ș",
    options: "Ă_Options_ș",
    defaultValue: "Ă_Default Value_ș",
    inputFeatureBy: "Ă_Input Feature by_ș",
    renderer: "Ă_Renderer_ș",
    displayType: "Ă_Display type_ș",
    label: "Ă_Label_ș",
    tooltip: "Ă_Tooltip_ș",
    visible: "Ă_Visible_ș",
    helpUrl: "Ă_Help URL_ș",
    useResultMapService: "Ă_Use the drawing options of result map service_ș",
    drawOnMap: "Ă_Interactively drawing on the map_ș",
    selectLayer: "Ă_Selecting a layer from the map_ș",
    url: "Ă_URL_ș",
    symbol: "Ă_Symbol_ș",
    shareResults: "Ă_Add result as operational layer_ș"
});