define({
		queries:"ก้_Queries_ษฺ",
		addNew: "ก้_Add New_ษฺ",
		setSource: "ก้_Set Source_ษฺ",
		setQuerySource: "ก้_Set query source_ษฺ",
		name: "ก้_Name_ษฺ",
		querySource: "ก้_Query Source_ษฺ",
		queryName:"ก้_Query Name_ษฺ",
		queryDefinition:"ก้_Query Definition_ษฺ",
		resultsSetting:"ก้_Results Setting_ษฺ",
		resultSettingTip:"ก้_Define below for showing information about features that are resulted from the query operation._ษฺ",
		resultItemTitle:"ก้_Result Item Title_ษฺ",
		resultItemContent:"ก้_Result Item Content_ษฺ",
		fieldsSetTip:"ก้_Check the fields you want to display. Select a field to change its alias,order it and format it._ษฺ",
		addField:"ก้_Add Field_ษฺ",
		visibility:"ก้_Visibility_ษฺ",
		alias:"ก้_Alias_ษฺ",
		specialType:"ก้_Special Type_ษฺ",
		actions:"ก้_Actions_ษฺ",
		none:"ก้_None_ษฺ",
		link:"ก้_Link_ษฺ",
		image:"ก้_Image_ษฺ",
		noField:"ก้_No field_ษฺ",
		operationalLayerTip:"ก้_Add result as operational layer_ษฺ",
		setLayerSymbolTip:"ก้_Set the symbol of query result._ษฺ",
		setSelectedSymbolTip:"ก้_Set the symbol of selected feature._ษฺ",
		notUseFilter:"ก้_Don't use filter_ษฺ",
		setSourceTip:"ก้_Please set query source !_ษฺ",
		setFilterTip:"ก้_Please set filter correctly !_ษฺ",
		ok:"ก้_Ok_ษฺ",
		cancel:"ก้_Cancel_ษฺ"
});