define({
    taskUrl: "ä_Task URL_Ü",
    serviceURLPlaceholder: "ä_Please input Geoprocessing task URL_Ü",
    ok: "ä_OK_Ü",
    cancel: "ä_Cancel_Ü",
    layer: "ä_Layer_Ü",
    action: "ä_Action_Ü",
    input: "ä_Input_Ü",
    output: "ä_Output_Ü",
    name: "ä_Name_Ü",
    type: "ä_Type_Ü",
    required: "ä_Required_Ü",
    layerOrder: "ä_Layer order_Ü",
    options: "ä_Options_Ü",
    defaultValue: "ä_Default Value_Ü",
    inputFeatureBy: "ä_Input Feature by_Ü",
    renderer: "ä_Renderer_Ü",
    displayType: "ä_Display type_Ü",
    label: "ä_Label_Ü",
    tooltip: "ä_Tooltip_Ü",
    visible: "ä_Visible_Ü",
    helpUrl: "ä_Help URL_Ü",
    useResultMapService: "ä_Use the drawing options of result map service_Ü",
    drawOnMap: "ä_Interactively drawing on the map_Ü",
    selectLayer: "ä_Selecting a layer from the map_Ü",
    url: "ä_URL_Ü",
    symbol: "ä_Symbol_Ü",
    shareResults: "ä_Add result as operational layer_Ü"
});