define({
    executeQueryTip: "æ_Click one of the following items to execute query._Â",
    invalidConfig: "æ_Invalid config. Please use Query setting page to get correct config._Â",
    queryParams: "æ_Query Parameters_Â",
    parameters: "æ_Parameters_Â",
    queries: "æ_Queries_Â",
    apply: "æ_Apply_Â",
    queryResults: "æ_Query Results_Â",
    clear: "æ_Clear_Â",
    noResults: "æ_No results_Â",
    queryError: "æ_Query failed !_Â",
    numberFound: "æ_Number of features found_Â",
    mapExtentTip:"æ_Limit the results to the current map extent._Â",
    noValue:"æ_No value_Â",
    and:"æ_and_Â",
    friendlyDatePattern:"æ_MM/dd/yyyy_Â",
    stringOperatorIs: "æ_is_Â", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "æ_is not_Â",
    stringOperatorStartsWith: "æ_starts with_Â",
    stringOperatorEndsWith: "æ_ends with_Â",
    stringOperatorContains: "æ_contains_Â",
    stringOperatorDoesNotContain: "æ_does not contain_Â",
    stringOperatorIsBlank: "æ_is blank_Â",
    stringOperatorIsNotBlank: "æ_is not blank_Â",
    dateOperatorIsOn: "æ_is on_Â", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "æ_is not on_Â",
    dateOperatorIsBefore: "æ_is before_Â",
    dateOperatorIsAfter: "æ_is after_Â",
    dateOperatorDays: "æ_days_Â",
    dateOperatorWeeks: "æ_weeks_Â", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "æ_months_Â",
    dateOperatorInTheLast: "æ_in the last_Â",
    dateOperatorNotInTheLast: "æ_not in the last_Â",
    dateOperatorIsBetween: "æ_is between_Â",
    dateOperatorIsNotBetween: "æ_is not between_Â",
    dateOperatorIsBlank: "æ_is blank_Â",
    dateOperatorIsNotBlank: "æ_is not blank_Â",
    numberOperatorIs: "æ_is_Â", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "æ_is not_Â",
    numberOperatorIsAtLeast: "æ_is at least_Â",
    numberOperatorIsLessThan: "æ_is less than_Â",
    numberOperatorIsAtMost: "æ_is at most_Â",
    numberOperatorIsGreaterThan: "æ_is greater than_Â",
    numberOperatorIsBetween: "æ_is between_Â",
    numberOperatorIsNotBetween: "æ_is not between_Â",
    numberOperatorIsBlank: "æ_is blank_Â",
    numberOperatorIsNotBlank: "æ_is not blank_Â"
});