define({
    showArcgisBasemaps: "한_Show ArcGIS Basemaps_빠",
    add: "한_Click to add a new basemap_빠",
    edit: "한_Properties_빠",
    title: "한_Title_빠",
    thumbnail: "한_Thumbnail_빠",
    thumbnailHint: "한_Click image to update_빠",
    url: "한_URL_빠",
    addlayer: "한_Add layer_빠",
    actions: "한_Actions_빠",
    warning: "한_Incorrect input_빠",
    save: "한_Back and Save_빠",
    back: "한_Back and Cancel_빠",
    addUrl: "한_Add URL_빠",
    autoCheck: "한_Auto Check_빠",
    checking: "한_Checking..._빠",
    ok: "한_OK_빠",
    cancel: "한_Cancel_빠",
    result: "한_Save successfully_빠",
    spError: "한_All basemaps added to the gallery need to have the same spatial reference._빠"
});