define({
    showArcgisBasemaps: "ł_Show ArcGIS Basemaps_ą",
    add: "ł_Click to add a new basemap_ą",
    edit: "ł_Properties_ą",
    title: "ł_Title_ą",
    thumbnail: "ł_Thumbnail_ą",
    thumbnailHint: "ł_Click image to update_ą",
    url: "ł_URL_ą",
    addlayer: "ł_Add layer_ą",
    actions: "ł_Actions_ą",
    warning: "ł_Incorrect input_ą",
    save: "ł_Back and Save_ą",
    back: "ł_Back and Cancel_ą",
    addUrl: "ł_Add URL_ą",
    autoCheck: "ł_Auto Check_ą",
    checking: "ł_Checking..._ą",
    ok: "ł_OK_ą",
    cancel: "ł_Cancel_ą",
    result: "ł_Save successfully_ą",
    spError: "ł_All basemaps added to the gallery need to have the same spatial reference._ą"
});