define({
    ok: "Ж_OK_Я",
    cancel: "Ж_Cancel_Я",
    exportMessage: "Ж_Export data to CSV file?_Я",
    exportFiles: "Ж_Export to CSV_Я",
    options: "Ж_Options_Я",
    zoomto: "Ж_Zoom to_Я",
    highlight: "Ж_Highlight Graphics_Я",
    selectAll: "Ж_Select All Pages_Я",
    selectPage: "Ж_Select Current Page_Я",
    clearSelection: "Ж_Clear Selection_Я",
    filterByExtent: "Ж_Filter by Map Extent_Я",
    refresh: "Ж_Refresh_Я",
    selected: "Ж_selected_Я",
    transparent: "Ж_Transparent Mode_Я",
    indicate: "Ж_Locate Selection_Я",
    columns: "Ж_Show/Hide Columns_Я",
    selectionSymbol: "Ж_Selection Symbol_Я",
    closeMessage: "Ж_Hide table[Show it again in layer list]_Я",
    dataNotAvailable: "Ж_Data not available!<br>Click [Refresh] button to have a try_Я"
});