define({
		queries:"ã_Queries_Ç",
		addNew: "ã_Add New_Ç",
		setSource: "ã_Set Source_Ç",
		setQuerySource: "ã_Set query source_Ç",
		name: "ã_Name_Ç",
		querySource: "ã_Query Source_Ç",
		queryName:"ã_Query Name_Ç",
		queryDefinition:"ã_Query Definition_Ç",
		resultsSetting:"ã_Results Setting_Ç",
		resultSettingTip:"ã_Define below for showing information about features that are resulted from the query operation._Ç",
		resultItemTitle:"ã_Result Item Title_Ç",
		resultItemContent:"ã_Result Item Content_Ç",
		fieldsSetTip:"ã_Check the fields you want to display. Select a field to change its alias,order it and format it._Ç",
		addField:"ã_Add Field_Ç",
		visibility:"ã_Visibility_Ç",
		alias:"ã_Alias_Ç",
		specialType:"ã_Special Type_Ç",
		actions:"ã_Actions_Ç",
		none:"ã_None_Ç",
		link:"ã_Link_Ç",
		image:"ã_Image_Ç",
		noField:"ã_No field_Ç",
		operationalLayerTip:"ã_Add result as operational layer_Ç",
		setLayerSymbolTip:"ã_Set the symbol of query result._Ç",
		setSelectedSymbolTip:"ã_Set the symbol of selected feature._Ç",
		notUseFilter:"ã_Don't use filter_Ç",
		setSourceTip:"ã_Please set query source !_Ç",
		setFilterTip:"ã_Please set filter correctly !_Ç",
		ok:"ã_Ok_Ç",
		cancel:"ã_Cancel_Ç"
});