define({
    ok: "ã_OK_Ç",
    cancel: "ã_Cancel_Ç",
    exportMessage: "ã_Export data to CSV file?_Ç",
    exportFiles: "ã_Export to CSV_Ç",
    options: "ã_Options_Ç",
    zoomto: "ã_Zoom to_Ç",
    highlight: "ã_Highlight Graphics_Ç",
    selectAll: "ã_Select All Pages_Ç",
    selectPage: "ã_Select Current Page_Ç",
    clearSelection: "ã_Clear Selection_Ç",
    filterByExtent: "ã_Filter by Map Extent_Ç",
    refresh: "ã_Refresh_Ç",
    selected: "ã_selected_Ç",
    transparent: "ã_Transparent Mode_Ç",
    indicate: "ã_Locate Selection_Ç",
    columns: "ã_Show/Hide Columns_Ç",
    selectionSymbol: "ã_Selection Symbol_Ç",
    closeMessage: "ã_Hide table[Show it again in layer list]_Ç",
    dataNotAvailable: "ã_Data not available!<br>Click [Refresh] button to have a try_Ç"
});