define({
    taskUrl: "כן_Task URL_ש",
    serviceURLPlaceholder: "כן_Please input Geoprocessing task URL_ש",
    ok: "כן_OK_ש",
    cancel: "כן_Cancel_ש",
    layer: "כן_Layer_ש",
    action: "כן_Action_ש",
    input: "כן_Input_ש",
    output: "כן_Output_ש",
    name: "כן_Name_ש",
    type: "כן_Type_ש",
    required: "כן_Required_ש",
    layerOrder: "כן_Layer order_ש",
    options: "כן_Options_ש",
    defaultValue: "כן_Default Value_ש",
    inputFeatureBy: "כן_Input Feature by_ש",
    renderer: "כן_Renderer_ש",
    displayType: "כן_Display type_ש",
    label: "כן_Label_ש",
    tooltip: "כן_Tooltip_ש",
    visible: "כן_Visible_ש",
    helpUrl: "כן_Help URL_ש",
    useResultMapService: "כן_Use the drawing options of result map service_ש",
    drawOnMap: "כן_Interactively drawing on the map_ש",
    selectLayer: "כן_Selecting a layer from the map_ש",
    url: "כן_URL_ש",
    symbol: "כן_Symbol_ש",
    shareResults: "כן_Add result as operational layer_ש"
});