define({
		queries:"Ř_Queries_ů",
		addNew: "Ř_Add New_ů",
		setSource: "Ř_Set Source_ů",
		setQuerySource: "Ř_Set query source_ů",
		name: "Ř_Name_ů",
		querySource: "Ř_Query Source_ů",
		queryName:"Ř_Query Name_ů",
		queryDefinition:"Ř_Query Definition_ů",
		resultsSetting:"Ř_Results Setting_ů",
		resultSettingTip:"Ř_Define below for showing information about features that are resulted from the query operation._ů",
		resultItemTitle:"Ř_Result Item Title_ů",
		resultItemContent:"Ř_Result Item Content_ů",
		fieldsSetTip:"Ř_Check the fields you want to display. Select a field to change its alias,order it and format it._ů",
		addField:"Ř_Add Field_ů",
		visibility:"Ř_Visibility_ů",
		alias:"Ř_Alias_ů",
		specialType:"Ř_Special Type_ů",
		actions:"Ř_Actions_ů",
		none:"Ř_None_ů",
		link:"Ř_Link_ů",
		image:"Ř_Image_ů",
		noField:"Ř_No field_ů",
		operationalLayerTip:"Ř_Add result as operational layer_ů",
		setLayerSymbolTip:"Ř_Set the symbol of query result._ů",
		setSelectedSymbolTip:"Ř_Set the symbol of selected feature._ů",
		notUseFilter:"Ř_Don't use filter_ů",
		setSourceTip:"Ř_Please set query source !_ů",
		setFilterTip:"Ř_Please set filter correctly !_ů",
		ok:"Ř_Ok_ů",
		cancel:"Ř_Cancel_ů"
});