define({
    showArcgisBasemaps: "ก้_Show ArcGIS Basemaps_ษฺ",
    add: "ก้_Click to add a new basemap_ษฺ",
    edit: "ก้_Properties_ษฺ",
    title: "ก้_Title_ษฺ",
    thumbnail: "ก้_Thumbnail_ษฺ",
    thumbnailHint: "ก้_Click image to update_ษฺ",
    url: "ก้_URL_ษฺ",
    addlayer: "ก้_Add layer_ษฺ",
    actions: "ก้_Actions_ษฺ",
    warning: "ก้_Incorrect input_ษฺ",
    save: "ก้_Back and Save_ษฺ",
    back: "ก้_Back and Cancel_ษฺ",
    addUrl: "ก้_Add URL_ษฺ",
    autoCheck: "ก้_Auto Check_ษฺ",
    checking: "ก้_Checking..._ษฺ",
    ok: "ก้_OK_ษฺ",
    cancel: "ก้_Cancel_ษฺ",
    result: "ก้_Save successfully_ษฺ",
    spError: "ก้_All basemaps added to the gallery need to have the same spatial reference._ษฺ"
});