define({
    executeQueryTip: "須_Click one of the following items to execute query._鷗",
    invalidConfig: "須_Invalid config. Please use Query setting page to get correct config._鷗",
    queryParams: "須_Query Parameters_鷗",
    parameters: "須_Parameters_鷗",
    queries: "須_Queries_鷗",
    apply: "須_Apply_鷗",
    queryResults: "須_Query Results_鷗",
    clear: "須_Clear_鷗",
    noResults: "須_No results_鷗",
    queryError: "須_Query failed !_鷗",
    numberFound: "須_Number of features found_鷗",
    mapExtentTip:"須_Limit the results to the current map extent._鷗",
    noValue:"須_No value_鷗",
    and:"須_and_鷗",
    friendlyDatePattern:"須_MM/dd/yyyy_鷗",
    stringOperatorIs: "須_is_鷗", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "須_is not_鷗",
    stringOperatorStartsWith: "須_starts with_鷗",
    stringOperatorEndsWith: "須_ends with_鷗",
    stringOperatorContains: "須_contains_鷗",
    stringOperatorDoesNotContain: "須_does not contain_鷗",
    stringOperatorIsBlank: "須_is blank_鷗",
    stringOperatorIsNotBlank: "須_is not blank_鷗",
    dateOperatorIsOn: "須_is on_鷗", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "須_is not on_鷗",
    dateOperatorIsBefore: "須_is before_鷗",
    dateOperatorIsAfter: "須_is after_鷗",
    dateOperatorDays: "須_days_鷗",
    dateOperatorWeeks: "須_weeks_鷗", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "須_months_鷗",
    dateOperatorInTheLast: "須_in the last_鷗",
    dateOperatorNotInTheLast: "須_not in the last_鷗",
    dateOperatorIsBetween: "須_is between_鷗",
    dateOperatorIsNotBetween: "須_is not between_鷗",
    dateOperatorIsBlank: "須_is blank_鷗",
    dateOperatorIsNotBlank: "須_is not blank_鷗",
    numberOperatorIs: "須_is_鷗", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "須_is not_鷗",
    numberOperatorIsAtLeast: "須_is at least_鷗",
    numberOperatorIsLessThan: "須_is less than_鷗",
    numberOperatorIsAtMost: "須_is at most_鷗",
    numberOperatorIsGreaterThan: "須_is greater than_鷗",
    numberOperatorIsBetween: "須_is between_鷗",
    numberOperatorIsNotBetween: "須_is not between_鷗",
    numberOperatorIsBlank: "須_is blank_鷗",
    numberOperatorIsNotBlank: "須_is not blank_鷗"
});