define({
    executeQueryTip: "ķ_Click one of the following items to execute query._ū",
    invalidConfig: "ķ_Invalid config. Please use Query setting page to get correct config._ū",
    queryParams: "ķ_Query Parameters_ū",
    parameters: "ķ_Parameters_ū",
    queries: "ķ_Queries_ū",
    apply: "ķ_Apply_ū",
    queryResults: "ķ_Query Results_ū",
    clear: "ķ_Clear_ū",
    noResults: "ķ_No results_ū",
    queryError: "ķ_Query failed !_ū",
    numberFound: "ķ_Number of features found_ū",
    mapExtentTip:"ķ_Limit the results to the current map extent._ū",
    noValue:"ķ_No value_ū",
    and:"ķ_and_ū",
    friendlyDatePattern:"ķ_MM/dd/yyyy_ū",
    stringOperatorIs: "ķ_is_ū", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "ķ_is not_ū",
    stringOperatorStartsWith: "ķ_starts with_ū",
    stringOperatorEndsWith: "ķ_ends with_ū",
    stringOperatorContains: "ķ_contains_ū",
    stringOperatorDoesNotContain: "ķ_does not contain_ū",
    stringOperatorIsBlank: "ķ_is blank_ū",
    stringOperatorIsNotBlank: "ķ_is not blank_ū",
    dateOperatorIsOn: "ķ_is on_ū", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "ķ_is not on_ū",
    dateOperatorIsBefore: "ķ_is before_ū",
    dateOperatorIsAfter: "ķ_is after_ū",
    dateOperatorDays: "ķ_days_ū",
    dateOperatorWeeks: "ķ_weeks_ū", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "ķ_months_ū",
    dateOperatorInTheLast: "ķ_in the last_ū",
    dateOperatorNotInTheLast: "ķ_not in the last_ū",
    dateOperatorIsBetween: "ķ_is between_ū",
    dateOperatorIsNotBetween: "ķ_is not between_ū",
    dateOperatorIsBlank: "ķ_is blank_ū",
    dateOperatorIsNotBlank: "ķ_is not blank_ū",
    numberOperatorIs: "ķ_is_ū", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "ķ_is not_ū",
    numberOperatorIsAtLeast: "ķ_is at least_ū",
    numberOperatorIsLessThan: "ķ_is less than_ū",
    numberOperatorIsAtMost: "ķ_is at most_ū",
    numberOperatorIsGreaterThan: "ķ_is greater than_ū",
    numberOperatorIsBetween: "ķ_is between_ū",
    numberOperatorIsNotBetween: "ķ_is not between_ū",
    numberOperatorIsBlank: "ķ_is blank_ū",
    numberOperatorIsNotBlank: "ķ_is not blank_ū"
});