define({
  root: {
    taskUrl: "Task URL",
    serviceURLPlaceholder: "Please input Geoprocessing task URL",
    ok: "OK",
    cancel: "Cancel",
    layer: "Layer",
    action: "Action",
    input: "Input",
    output: "Output",
    name: "Name",
    type: "Type",
    required: "Required",
    layerOrder: "Layer order",
    options: "Options",
    defaultValue: "Default Value",
    inputFeatureBy: "Input Feature by",
    renderer: "Renderer",
    displayType: "Display type",
    label: "Label",
    tooltip: "Tooltip",
    visible: "Visible",
    helpUrl: "Help URL",
    useResultMapService: "Use the drawing options of result map service",
    drawOnMap: "Interactively drawing on the map",
    selectLayer: "Selecting a layer from the map",
    url: "URL",
    symbol: "Symbol",
    shareResults: "Add result as operational layer"
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": true
});