define({
  root: {
    titleBasemap: 'Basemaps',
    titleLayers: 'Operational Layers',
    labelLayer: 'Layer Name',
    itemZoomTo: 'Zoom to',
    itemTransparency: 'Transparency',
    itemTransparent: 'Transparent',
    itemOpaque: 'Opaque',
    itemMoveUp: 'Move up',
    itemMoveDown: 'Move down',
    itemDesc: 'Description',
    itemDownload: 'Download',
    itemToAttributeTable: 'Open Attribute Table'
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  'zh-cn': true
});
